### ISSUE TITLE
Error testing Cubic EOS physical property package

### ISSUE THREAD

**Issue by tony121psu** [Pyomo/pyomo#104]
I’m receiving an unexpected error (see below) when trying to test the cubic equation of state property package. I’m running the following file: models/idaes_models/properties/physical/testbed_cubic.py. 
Would anyone know what might be causing the error (or how to fix it)? John E, Andrew, and I are stumped. Curiously enough, this code runs without errors on Andrew’s computer. 

Traceback (most recent call last):

  File "<ipython-input-1-357feda925be>", line 1, in <module>
    runfile('/home/tburgard/models-master/idaes_models/properties/physical/testbed_cubic.py', wdir='/home/tburgard/models-master/idaes_models/properties/physical')

  File "/home/tburgard/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/home/tburgard/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/home/tburgard/models-master/idaes_models/properties/physical/testbed_cubic.py", line 119, in <module>
    main()

  File "/home/tburgard/models-master/idaes_models/properties/physical/testbed_cubic.py", line 93, in main
    fs_obj = Flowsheet()

  File "/home/tburgard/models-master/idaes_models/properties/physical/testbed_cubic.py", line 31, in __init__
    self.add_unit("P1", prop(phases='VL',mix_props=1))

  File "PR_ASU.py", line 149, in __init__
    mix_props=self.mix_props)

  File "Cubic_EoS.py", line 86, in build
    self._make_EoS_coeff()

  File "Cubic_EoS.py", line 244, in _make_EoS_coeff
    for j in blk.comp) for i in blk.comp))

  File "Cubic_EoS.py", line 244, in <genexpr>
    for j in blk.comp) for i in blk.comp))

  File "Cubic_EoS.py", line 244, in <genexpr>
    for j in blk.comp) for i in blk.comp))

  File "/home/tburgard/anaconda2/lib/python2.7/site-packages/pyomo/core/base/indexed_component.py", line 461, in __getitem__
    "not been constructed." % ( self.name, idx_str,) )

ValueError: Error retrieving component IndexedVar[N2]: The component has not been constructed.
---------------------------------------------------------------
The part of the code causing this error is pasted below (line 244 is the last line):
# Constraints
        # Pressure independent coefficients
        if blk.flag_phases != 'V':
            blk.eq_am_liq = Constraint(expr = blk.am_liq == sum(sum(
                            blk.x[i]*blk.x[j]
                            * sqrt(blk.a[i]*blk.a[j])
                            * (1-blk.kappa[i][j])
                            for j in blk.comp) for i in `blk.comp))

**Comment by tony121psu** [comment]
I think there's a better location for this question...sorry
