### ISSUE TITLE
Version 5.6.4: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1286: ordinal not in range(128)

### ISSUE THREAD

**Issue by yurivict** [Pyomo/pyomo#1044]
```
===>  Configuring for py36-Pyomo-5.6.4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 206, in <module>
    run_setup()
  File "setup.py", line 137, in run_setup
    long_description=read('README.md'),
  File "setup.py", line 43, in read
    line = README.readline()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1286: ordinal not in range(128)
*** Error code 1

```

FreeBSD 12

**Comment by ghackebeil** [comment]
@yurivict. Thanks for reporting this. We will try to get a fixed release on to PyPI ASAP.
