### ISSUE TITLE
DataPortal empty index set bug

### ISSUE THREAD

**Issue by Oriloni** [Pyomo/pyomo#1083]
An error occurs when passing an empty parameter matrix to an abstract model through DataPortal:

For example, for m=0 this code
```
model.m = Param(within=NonNegativeIntegers)
model.I_m = RangeSet(1, model.m)
model.A_Z = Param(model.I_m, model.M_Z)
```
produces the following error:

```
ERROR: Constructing component 'A_Z' from data={None: 'I_m'} failed:
        RuntimeError: Failed to set value for param=A_Z, index=None,
        value=I_m.
        source error message="Index 'None' is not valid for indexed component
        'A_Z'"
Traceback (most recent call last):
  File "/home/galina/anaconda3/lib/python3.7/site-packages/pyomo/core/base/param.py", line 878, in construct
    self._validate_index(key), val)
  File "/home/galina/anaconda3/lib/python3.7/site-packages/pyomo/core/base/indexed_component.py", line 502, in _validate_index
    % ( idx, self.name, ))
KeyError: "Index 'None' is not valid for indexed component 'A_Z'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "algorithmus.py", line 92, in <module>
    instance = model.create_instance(data) #, report_timing=True)
  File "/home/galina/anaconda3/lib/python3.7/site-packages/pyomo/core/base/PyomoModel.py", line 735, in create_instance
    profile_memory=profile_memory )
  File "/home/galina/anaconda3/lib/python3.7/site-packages/pyomo/core/base/PyomoModel.py", line 818, in load
    profile_memory=profile_memory)
  File "/home/galina/anaconda3/lib/python3.7/site-packages/pyomo/core/base/PyomoModel.py", line 882, in _load_model_data
    self._initialize_component(modeldata, namespaces, component_name, profile_memory)
  File "/home/galina/anaconda3/lib/python3.7/site-packages/pyomo/core/base/PyomoModel.py", line 936, in _initialize_component
    declaration.construct(data)
  File "/home/galina/anaconda3/lib/python3.7/site-packages/pyomo/core/base/param.py", line 890, in construct
    % (self.name, str(key), str(val), str(msg)) )
RuntimeError: Failed to set value for param=A_Z, index=None, value=I_m.
        source error message="Index 'None' is not valid for indexed component 'A_Z'"
```

A_Z is a .csv file containing only index declaration I_m and is loaded into a DataPortal object. An empty A_Z.csv fails to be loaded too:
```
  File "algorithmus.py", line 49, in <module>
    data.load(filename=directory+'A_Z.csv', param=model.A_Z, format='array')
  File "/home/galina/anaconda3/lib/python3.7/site-packages/pyomo/dataportal/DataPortal.py", line 163, in load
    self._data_manager.read()
  File "/home/galina/anaconda3/lib/python3.7/site-packages/pyomo/dataportal/plugins/csv_table.py", line 52, in read
    self._info = ["param",p,":=",tmp[0][0]]
IndexError: list index out of range
```

**Comment by optimaldecisiondynamics** [comment]
I came across this when I had the same problem.  For context, my use-case is that when generating an instance from an abstract model some constraints may not apply (i.e., they won't exist).  The design is to create empty index sets where this is the case.

I came up with a workaround solution and wanted to post it in case others experience the same issue.  My general approach and example code are below.  My code constitutes a simple toy model for demonstrative purposes.

**General Approach:**
- Leverage Pyomo's desirable behavior that empty index sets (and thus other model objects such as parameters or constraints) are permitted in abstract models.
- Leverage Pyomo's desirable behavior that an instance of an abstract model **need not** have all model components populated to successfully generate.
- Only import (by way of a data portal) an empty index set **IF** there is at least 1 row in the associated data source.  Otherwise skip the data import altogether.  Specifically, I check the number of rows of the imported pandas dataframe first.
- By skipping the import, the model component is unpopulated (i.e., `size = 0`) and the instance can be created.

**Code:**
```
############################ SETUP ########################################
from pyomo.environ import *
import os
import pandas as pd

model = AbstractModel()

############################## SETS #########################################

model.PRODUCTS = Set()

model.LIMITED_PRODUCTS = Set(within = model.PRODUCTS)

################################ PARAMETERS ###################################

model.PROFIT = Param(model.PRODUCTS)

model.COST = Param(model.PRODUCTS)

model.SUPPLY = Param(model.LIMITED_PRODUCTS)

########################## DECISION VARIABLES #################################

model.PRODUCTION = Var(model.PRODUCTS, within = NonNegativeIntegers)

############################### OBJECTIVE FUNCTION #############################

def total_profit_rule(model):
    return sum(model.PROFIT[p] * model.PRODUCTION[p] for p in model.PRODUCTS)
model.total_profit = Objective(rule = total_profit_rule, sense = maximize)

########################### CONSTRAINTS ########################################

def total_cost_rule(model, p):
    return sum(model.COST[p] * model.PRODUCTION[p] for p in model.PRODUCTS) <= 100
model.total_cost = Constraint(model.PRODUCTS, rule = total_cost_rule)

def limited_supply_rule(model, l):
    return model.PRODUCTION[l] <= model.SUPPLY[l]
model.limited_supply = Constraint(model.LIMITED_PRODUCTS, rule = limited_supply_rule)

#################### POPULATE WITH DATA AND CREATE MODEL INSTANCE ###################

wd = os.path.abspath('')

current_dir = wd + '\\'

# Read in data to create problem instance
data = DataPortal()

data.load(filename = current_dir + 'test_problem_financials.csv', param = (model.COST, model.PROFIT), index = model.PRODUCTS)

# This may be empty, i.e., contain 0 rows
# Specifically, model.LIMITED_PRODUCTS may have cardinality 0
# Test it!
# Use the data portal if there is at least 1 row, otherwise skip the data import altogether
limited_products_set_test = pd.read_csv('test_problem_supply.csv')
if limited_products_set_test.shape[0] > 0:
    data.load(filename = current_dir + 'test_problem_supply.csv', param = (model.SUPPLY), index = model.LIMITED_PRODUCTS)

# Create model instance
instance = model.create_instance(data, report_timing=True)

instance.pprint()

################################ SOLVE ####################################
# solve
SolverFactory('cbc',).solve(instance, tee = True).write()
```

The above code assumes the existence of two CSV files: `test_problem_financials.csv` and `test_problem_supply.csv`.  If we have a non-empty set `model.LIMITED_PRODUCTS` (products for which we can produce only a limited supply) we will see that the solution changes as compared to when the set is empty (i.e., `test_problem_supply.csv` has just a header but 0 rows).

Hope this helps,
Louis

**Comment by mrmundt** [comment]
In an effort to clean up issues, we are moving some discussions to our [Archived Design Discussions wiki](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions).
