### ISSUE TITLE
Block set_value can't assign to index of an IndexedBlock

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#1106]
Calling set_value on a Block fails when assigning either a Block or a BlockData to an index in an IndexedBlock.

If you assign a Block:
```
m = ConcreteModel()
m.block_list = Block([1, 2])

movingBlock = m.some_other_block = Block()
m.del_component(movingBlock)

m.block_list[1] = movingBlock
```
```
Traceback (most recent call last):
  File "blockSetValue.py", line 11, in <module>
    m.block_list[1] = movingBlock
  File "/home/esjohn/src/pyomo/pyomo/core/base/indexed_component.py", line 412, in __setitem__
    return self._setitem_when_not_present(index, val)
  File "/home/esjohn/src/pyomo/pyomo/core/base/indexed_component.py", line 675, in _setitem_when_not_present
    obj.set_value(value)
  File "/home/esjohn/src/pyomo/pyomo/core/base/block.py", line 711, in set_value
    self.add_component(k,val[k])
  File "/home/esjohn/src/pyomo/pyomo/core/base/block.py", line 923, in add_component
    super(_BlockData, self).__setattr__(name, val)
TypeError: attribute name must be string, not 'NoneType'
```
If you assign a BlockData:
```
m = ConcreteModel()
m.block_list = Block(Any)

m.some_other_block_list = Block([3,4])
movingBlock = m.some_other_block_list[4]
m.del_component(movingBlock)

m.block_list[len(m.block_list)] = movingBlock
```
```
Traceback (most recent call last):
  File "blockSetValue.py", line 21, in <module>
    m.block_list[len(m.block_list)] = movingBlock
  File "/home/esjohn/src/pyomo/pyomo/core/base/indexed_component.py", line 412, in __setitem__
    return self._setitem_when_not_present(index, val)
  File "/home/esjohn/src/pyomo/pyomo/core/base/indexed_component.py", line 675, in _setitem_when_not_present
    obj.set_value(value)
  File "/home/esjohn/src/pyomo/pyomo/core/base/block.py", line 710, in set_value
    for k in sorted(iterkeys(val)):
  File "/projects/sems/install/rhel6-x86_64/pyomo/python/six/1.11.0/lib/python2.7/site-packages/six.py", line 599, in iterkeys
    return d.iterkeys(**kw)
  File "/home/esjohn/src/pyomo/pyomo/core/base/block.py", line 549, in __getattr__
    % (self.__class__.__name__, val))
AttributeError: '_BlockData' object has no attribute 'iterkeys'
```

**Comment by jsiirola** [comment]
Interesting.  Neither of these examples are producing exceptions for me.  For your second example, there is something weird going on, as the `del_component` is removing the *entire* `some_other_block_list` and not just the individual _BlockData.  That is probably a bug.  That said, for the second example, I think you want to:

```
del movingBlock.parent_component()[movingBlock.index()]
```

**Comment by jsiirola** [comment]
Note that the resolution of this issue was to *disable* the assignment of one block to another and instead to implement two new Block methods:
- `clear()` removes all user-defined attributes and components
- `transfer_attributes_from()` to move the attributes/components from one Block to another.
