### ISSUE TITLE
Set Rewrite Integration TODO's

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#1112]
When integrating the set rewrite with the rest of Pyomo, we need to:

- check the implementation of `IndexedComponent.__iter__`. See the following example for details.
```
>>> import pyomo.environ as pe
>>> from pyomo.core.base.set import Set
>>> m = pe.ConcreteModel()
>>> m.a = Set(initialize=[1,2,3])
>>> list(m.a.values())
[1, 2, 3]
>>> list(m.a.cross(m.a).values())
Traceback (most recent call last):
  File "/Users/mlbynum/Documents/pyomo_big/pyomo_main/pyomo/core/base/set.py", line 902, in _to_0_based_index
    if item != int(item):
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mlbynum/Documents/pyomo_big/pyomo_main/pyomo/core/base/indexed_component.py", line 356, in itervalues
    yield self[key]
  File "/Users/mlbynum/Documents/pyomo_big/pyomo_main/pyomo/core/base/set.py", line 2780, in __getitem__
    _idx = self._to_0_based_index(index)
  File "/Users/mlbynum/Documents/pyomo_big/pyomo_main/pyomo/core/base/set.py", line 910, in _to_0_based_index
    % (self.name, type(item).__name__,))
IndexError: SetProduct_OrderedSet indices must be integers, not tuple
```

**Comment by jsiirola** [comment]
The issue here is that Set has historically supported `__getitem__` as an alias for `card()`.  Unfortunately, that behavior is documented in the book.  I think we should deprecate `__getitem__` for ordered sets and replace it in with `card()`, even if we can't remove that functionality until Pyomo 7.
