### ISSUE TITLE
AttributeError when running install-extras on Fedora 30

### ISSUE THREAD

**Issue by jg110** [Pyomo/pyomo#1117]
When running `pyomo install-extras` after installing Pyomo via `pip3 install --user pyomo` I get the following error:

```
$ pyomo install-extras
 
------------------------------------------------------------
Installation Output Logs
  (A summary will be printed below)
------------------------------------------------------------
 
Traceback (most recent call last):
  File "/home/jg110/.local/lib/python3.7/site-packages/pyomo/scripting/plugins/extras.py", line 80, in install_extras
    pip.logger.consumers = []
AttributeError: module 'pip' has no attribute 'logger'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jg110/.local/bin/pyomo", line 10, in <module>
    sys.exit(main_console_script())
  File "/home/jg110/.local/lib/python3.7/site-packages/pyomo/scripting/pyomo_main.py", line 92, in main_console_script
    ans = main()
  File "/home/jg110/.local/lib/python3.7/site-packages/pyomo/scripting/pyomo_main.py", line 82, in main
    retval = _options.func(_options)
  File "/home/jg110/.local/lib/python3.7/site-packages/pyomo/scripting/plugins/extras.py", line 100, in pyomo_subcommand
    return install_extras(options.args, quiet=options.quiet)
  File "/home/jg110/.local/lib/python3.7/site-packages/pyomo/scripting/plugins/extras.py", line 83, in install_extras
    pip.log.consumers = []
AttributeError: module 'pip' has no attribute 'log'
```

This occurs on Fedora 30. It may be related to Fedora's convention of adding a version number suffix to some executables, e.g. `pip` refers to the Python 2 pip version and `pip3` refers to the Python 3 pip version.

**Comment by jschelbert** [comment]
Hi, I have the same error on MacOs 10.14 when using a pyenv Python 3.7.3 installation.
```
------------------------------------------------------------
Installation Output Logs
  (A summary will be printed below)
------------------------------------------------------------
 
Traceback (most recent call last):
  File "/Users/XXXXXXXXXX.pyenv/versions/3.7.3/lib/python3.7/site-packages/pyomo/scripting/plugins/extras.py", line 80, in install_extras
    pip.logger.consumers = []
AttributeError: module 'pip' has no attribute 'logger'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/XXXXXXXXXX/.pyenv/versions/3.7.3/bin/pyomo", line 10, in <module>
    sys.exit(main_console_script())
  File "/Users/XXXXXXXXXX/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pyomo/scripting/pyomo_main.py", line 92, in main_console_script
    ans = main()
  File "/Users/XXXXXXXXXX/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pyomo/scripting/pyomo_main.py", line 82, in main
    retval = _options.func(_options)
  File "/Users/XXXXXXXXXX/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pyomo/scripting/plugins/extras.py", line 100, in pyomo_subcommand
    return install_extras(options.args, quiet=options.quiet)
  File "/Users/XXXXXXXXXX/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pyomo/scripting/plugins/extras.py", line 83, in install_extras
    pip.log.consumers = []
AttributeError: module 'pip' has no attribute 'log'
```

**Comment by juanfung** [comment]
Same error on linux a docker image with python 3.6 (`python:3.6-slim-buster`)

**Comment by qtothec** [comment]
There has been some thought about moving away from `install-extras`. You can still get the same "extras" by installing the relevant packages, and for those on conda, many are already installed.

**Comment by cerofrais** [comment]
I am facing the same issue in windows as well via pip.

**Comment by blnicho** [comment]
`install-extras` has been deprecated so closing this
