### ISSUE TITLE
PySP errors with networkx 2.4

### ISSUE THREAD

**Issue by jsiirola** [Pyomo/pyomo#1138]
I recently rebuilt the Travis docker images to include an additional package (pathos, see #1122).  As part of that rebuild, some of the docker images picked up a newer version of `networkx` (2.4 instead of 2.3), which appears to have triggered a slew of PySP test failures, e.g.:
```
======================================================================
ERROR: test_bundles (pyomo.pysp.tests.unit.test_scenariotree.TestScenarioTreeFromNetworkX)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Pyomo/pyomo/pyomo/pysp/tests/unit/test_scenariotree.py", line 745, in test_bundles
    edge_probability_attribute=None)
  File "/home/travis/build/Pyomo/pyomo/pyomo/pysp/scenariotree/tree_structure_model.py", line 313, in ScenarioTreeModelFromNetworkX
    networkx.dfs_successors(tree, root))
  File "/home/travis/build/Pyomo/pyomo/pyomo/pysp/scenariotree/tree_structure_model.py", line 296, in _setup
    _setup(v, succ)
  File "/home/travis/build/Pyomo/pyomo/pyomo/pysp/scenariotree/tree_structure_model.py", line 311, in _setup
    tree.node[u].get('bundle', None)
AttributeError: 'DiGraph' object has no attribute 'node'
```

For a full build, see: https://travis-ci.org/Pyomo/pyomo/jobs/597959028

@ghackebeil: is this a relatively easy fix, or should we rebuild the Docker images and pin to a `networkx` version before 2.4?

**Comment by ghackebeil** [comment]
I can’t imagine it’s too difficult of a fix. I’ll take a look.
