### ISSUE TITLE
DeveloperError when using a singleton set as a index for an IndexedConstraint

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#116]
See small example below:
```
qichen@QC-CMU-Tower:~$ pyothon
Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyomo.environ import *
>>> m = ConcreteModel()
>>> m.s = Set(initialize=['one'])
>>> m.c = Constraint(m.s)
>>> m.c[m.s].deactivate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/core/base/indexed_component.py", line 492, in __getitem__
    return self._default(ndx)
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/core/base/indexed_component.py", line 655, in _default
    % (self.__class__.__name__,))
pyomo.util._config.DeveloperError: Internal Pyomo implementation error:
	'Derived component IndexedConstraint failed to define _default().'
	Please report this to the Pyomo Developers.
>>> 
```
On the other hand, nothing breaks when I try to do the same thing with IndexedVar
```
>>> from pyomo.environ import *
>>> m = ConcreteModel()
>>> m.s = Set(initialize=['one'])
>>> m.x = Var(m.s, initialize=1)
>>> m.x.display()
x : Size=1, Index=s
    Key : Lower : Value : Upper : Fixed : Stale : Domain
    one :  None :     1 :  None : False : False :  Reals
>>> m.x[m.s].display()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_GeneralVarData' object has no attribute 'display'
>>> m.x[m.s].deactivate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_GeneralVarData' object has no attribute 'deactivate'
>>> 
```

**Comment by jsiirola** [comment]
#133 "fixed" the Constraint example, although it will still generate an error:
```
>>> from pyomo.environ import *
>>> m = ConcreteModel()
>>> m.s = Set(initialize=['one'])
>>> m.c = Constraint(m.s)
>>> m.c[m.s].deactivate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jdsiiro/Research/pyomo/pyomo/core/base/indexed_component.py", line 555, in __getitem__
    return self._getitem_when_not_present(index)
  File "/home/jdsiiro/Research/pyomo/pyomo/core/base/indexed_component.py", line 839, in _getitem_when_not_present
    raise KeyError(index)
KeyError: <pyomo.core.base.sets.SimpleSet object at 0x7f71d75a5d60>
```
This is the correct behavior, as you are attempting to deactivate a Constraint that does not exist.  This does not generate an error for Var, as Var are constructed dense by default (and there is a sensible thing to do if the Var was sparse and the user requested an undefined index).

That said, your Var example is still broken: `m.x[m.s].display()` should generate a `KeyError`, instead it actually creates a `_VarData` and stores it into the Var.  This should not be allowed, because the `Set` `m.s` is not a member itself!  The problem can be highlighted by pprinting the Var after the error:
```
>>> m.x.display()
x : Size=2, Index=s
    Key : Lower : Value : Upper : Fixed : Stale : Domain
      s :  None :     1 :  None : False : False :  Reals
    one :  None :     1 :  None : False : False :  Reals
```
I suspect that this is actually a problem with Set, where `m.s in m.s == True`.

**Comment by qtothec** [comment]
Yeah, I'm fine with getting an error message here, as long as it makes sense. I came across this while more or less messing around.
