### ISSUE TITLE
Deceptive error message for index mismatch using Decorator syntax

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#1193]
One of my collaborators recently stumbled upon a confusing traceback. The mistake was a mismatch in the number of sets and the number of indices:

```
@block.Constraint(m.A, m.B)
def foo(m, a, b, c):
    return ...
```

The error message is reasonable **if** you are a programmer:
```
Traceback (most recent call last):
  File "/home/qichen/git/pyomo/pyomo/core/base/misc.py", line 57, in apply_indexed_rule
    return rule(model, *index)
TypeError: foo() missing 1 required positional argument: 'c'

During handling of the above exception, another exception occurred:
...
```
But I think that it would be clearer for modelers to mention that the expected number of indices don't line up, because at the end of the very long stack trace was:

```
RuntimeError: Cannot add component 'no_flow_index'
(type <class 'pyomo.core.base.sets._SetProduct'>)
to block 'column_inactive[C1]': a component by that name
(type <class 'pyomo.core.base.sets._SetProduct'>) is already defined.
```

which is entirely unrelated to the true issue.

<details>
<summary>Full traceback</summary>

```
Traceback (most recent call last):
  File "/home/qichen/git/pyomo/pyomo/core/base/misc.py", line 57, in apply_indexed_rule
    return rule(model, *index)
TypeError: no_task_flow() missing 1 required positional argument: 'k'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qichen/git/pyomo/pyomo/core/base/misc.py", line 72, in apply_indexed_rule
    return rule(model)
TypeError: no_task_flow() missing 3 required positional arguments: 'n', 'i', and 'k'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qichen/git/pyomo/pyomo/core/base/misc.py", line 61, in apply_indexed_rule
    return rule(model, index)
  File "/home/qichen/git/circular/main2.py", line 252, in column_inactive
    @col_inactive.Constraint(m.special_streams, m.components)
  File "/home/qichen/git/pyomo/pyomo/core/base/block.py", line 100, in __call__
    self._component(*self._args, rule=rule, **(self._kwds))
  File "/home/qichen/git/pyomo/pyomo/core/base/block.py", line 570, in __setattr__
    self.add_component(name, val)
  File "/home/qichen/git/pyomo/pyomo/core/base/block.py", line 1010, in add_component
    val.construct(data)
  File "/home/qichen/git/pyomo/pyomo/core/base/constraint.py", line 779, in construct
    ndx)
  File "/home/qichen/git/pyomo/pyomo/core/base/misc.py", line 80, in apply_indexed_rule
    return rule(model, *index)
TypeError: no_task_flow() missing 1 required positional argument: 'k'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qichen/git/pyomo/pyomo/core/base/misc.py", line 72, in apply_indexed_rule
    return rule(model)
TypeError: column_inactive() missing 1 required positional argument: 'j'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qichen/git/circular/main2.py", line 310, in <module>
    m = build_model()
  File "/home/qichen/git/circular/main2.py", line 246, in build_model
    @m.Disjunct(m.columns)
  File "/home/qichen/git/pyomo/pyomo/core/base/block.py", line 100, in __call__
    self._component(*self._args, rule=rule, **(self._kwds))
  File "/home/qichen/git/pyomo/pyomo/core/base/block.py", line 570, in __setattr__
    self.add_component(name, val)
  File "/home/qichen/git/pyomo/pyomo/core/base/block.py", line 1010, in add_component
    val.construct(data)
  File "/home/qichen/git/pyomo/pyomo/core/base/block.py", line 1824, in construct
    self, self._rule, _block, idx, self._options)
  File "/home/qichen/git/pyomo/pyomo/core/base/misc.py", line 84, in apply_indexed_rule
    return rule(model, index)
  File "/home/qichen/git/circular/main2.py", line 248, in column_inactive
    @col_inactive.Constraint(m.special_streams, m.components)
  File "/home/qichen/git/pyomo/pyomo/core/base/block.py", line 100, in __call__
    self._component(*self._args, rule=rule, **(self._kwds))
  File "/home/qichen/git/pyomo/pyomo/core/base/block.py", line 600, in __setattr__
    self.add_component(name, val)
  File "/home/qichen/git/pyomo/pyomo/core/base/block.py", line 910, in add_component
    self._add_temporary_set(val)
  File "/home/qichen/git/pyomo/pyomo/core/base/block.py", line 733, in _add_temporary_set
    self._construct_temporary_set(val._index, val.local_name + "_index")
  File "/home/qichen/git/pyomo/pyomo/core/base/block.py", line 757, in _construct_temporary_set
    self.add_component(name, obj)
  File "/home/qichen/git/pyomo/pyomo/core/base/block.py", line 864, in add_component
    % (name, type(val), self.name, type(getattr(self, name))))
RuntimeError: Cannot add component 'no_flow_index' (type <class 'pyomo.core.base.sets._SetProduct'>) to block 'column_inactive[C1]': a component by that name (type <class 'pyomo.core.base.sets._SetProduct'>) is already defined.
```
</details>

**Comment by blnicho** [comment]
This was resolved at some point. This example no longer produces a very long stack trace.
