### ISSUE TITLE
BARON Unicode Decode Error

### ISSUE THREAD

**Issue by JoseMacherone** [Pyomo/pyomo#1275]
When solving a model using:

```
instance = model.create_instance()
opt = SolverFactory('baron')
solver_results = opt.solve(instance,  options_string="MaxTime=-1", tee = True)
```
I get the following error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\56978\AppData\Local\Continuum\anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\56978\AppData\Local\Continuum\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\56978\AppData\Local\Continuum\anaconda3\lib\site-packages\pyutilib\subprocess\processmngr.py", line 380, in _merged_reader
    char = s.data.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 0: unexpected end of data
```
This doesn't prevent me from getting the optimal solution, but i can't get to see the solver output. Please let me know if you have any ideas on know how to fix this.

**Comment by blnicho** [comment]
What version of Pyomo are you using?

**Comment by JoseMacherone** [comment]
Pyomo 5.6.8 and BARON 18.8.23

**Comment by blnicho** [comment]
Could you share the model or a minimal example that recreates the error?

**Comment by JoseMacherone** [comment]
It appears the error does not depend on the model. This is an example i've been trying to implement:

```
from pyomo.environ import *

model = AbstractModel()
model.M = RangeSet(0, 10)
model.K =  Param(default = 3)
model.x = Var(model.M, domain = Binary)

def objexpression(model):
    return sum(model.x[m] for m in model.M)

model.OBJ = Objective(rule = objexpression)

def limiteMesas(model):
    return sum(model.x[m] for m in model.M) >= model.K

model.limiteMesas = Constraint(rule = limiteMesas)

instance = model.create_instance()
opt = SolverFactory('baron')
solver_results = opt.solve(instance,  options_string="MaxTime=-1", tee = True)
```

**Comment by qtothec** [comment]
Also potentially relevant: are you on Windows?
