### ISSUE TITLE
AttributeErrors when adding variables/constraints to (Gurobi) persistent solver

### ISSUE THREAD

**Issue by e-dorigatti** [Pyomo/pyomo#1297]
I am trying to modify a model by adding variables/constraints and re-solving the updated model, following [the guide](https://pyomo.readthedocs.io/en/stable/advanced_topics/persistent_solvers.html).

The problem is that both cases fail with attribute errors, for a variable:
```
Traceback (most recent call last):
  File "seqdesign.py", line 98, in <module>
    main()
  File "seqdesign.py", line 71, in main
    problem._solver.add_var(problem._model.McBernoulliTrials)
  File "/home/edo/miniconda3/envs/spacers/lib/python3.7/site-packages/pyomo/solvers/plugins/solvers/persistent_solver.py", line 153, in add_var
    self._add_var(var)
  File "/home/edo/miniconda3/envs/spacers/lib/python3.7/site-packages/pyomo/solvers/plugins/solvers/gurobi_direct.py", line 208, in _add_var
    vtype = self._gurobi_vtype_from_var(var)
  File "/home/edo/miniconda3/envs/spacers/lib/python3.7/site-packages/pyomo/solvers/plugins/solvers/gurobi_direct.py", line 377, in _gurobi_vtype_from_var
    if var.is_binary():
AttributeError: 'IndexedVar' object has no attribute 'is_binary'
```

And for a constraint:

```
Traceback (most recent call last):
  File "seqdesign.py", line 98, in <module>
    main()
  File "seqdesign.py", line 71, in main
    problem._solver.add_constraint(problem._model.McBernoulliTrialsSetPositive)
  File "/home/edo/miniconda3/envs/spacers/lib/python3.7/site-packages/pyomo/solvers/plugins/solvers/persistent_solver.py", line 132, in add_constraint
    self._add_constraint(con)
  File "/home/edo/miniconda3/envs/spacers/lib/python3.7/site-packages/pyomo/solvers/plugins/solvers/gurobi_direct.py", line 272, in _add_constraint
    if is_fixed(con.body):
AttributeError: 'IndexedConstraint' object has no attribute 'body'
```

Is the problem that I am using indexed variables and constraints? How to make this work without migrating all code from `pyomo.environ` to `pyomo.core`?

NB: I asked this [on stackoverflow](https://stackoverflow.com/questions/60152759/attributeerrors-when-adding-variables-constraints-to-gurobi-persistent) a week ago, but did not receive attention.

**Comment by michaelbynum** [comment]
You cannot pass an `IndexedVar` or and `IndexedConstraint` into the `add_var` and `add_constraint` methods. You have to loop over the individual variables and constraints and add them one at a time:

```
for v in my_var.values():
    solver.add_var(v)

for c in my_con.values():
    solver.add_constraint(c)
```

Additionally, you can check if a variable or constraint is indexed with `my_var.is_indexed()` or `my_con.is_indexed()`.

**Comment by e-dorigatti** [comment]
Thank you. I wanted to propose a PR to add this functionality, then I saw it was [removed](https://github.com/Pyomo/pyomo/pull/366) some time ago. Can I instead add this trick to [the documentation](https://github.com/Pyomo/pyomo/blob/7899f8dad22343a8f6db8c6175cc3744de84027b/doc/OnlineDocs/advanced_topics/persistent_solvers.rst)?

**Comment by michaelbynum** [comment]
Yes, pull requests are always welcome, especially for documentation!
