### ISSUE TITLE
ampl_.py NL filewriter throwing ValueError for LinearExpression type (5.6.9 dev)

### ISSUE THREAD

**Issue by natalieisenberg** [Pyomo/pyomo#1301]
Here's an example to reproduce the error:

```
from pyomo.environ import *
m = ConcreteModel()
m.x = Var(initialize=1, bounds=(0,3))
m.obj = Objective(expr=(m.x - 3)**2)
solver = SolverFactory('ipopt')
results = solver.solve(m)
```

Stack trace: (note the "exit general" and "TODO" are from new_standard_repn.py)
```
exit general
TODO: Separate Linear and Nonlinear terms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nisenber/Documents/CODE/pyomo/pyomo/opt/base/solvers.py", line 573, in solve
    self._presolve(*args, **kwds)
  File "/home/nisenber/Documents/CODE/pyomo/pyomo/opt/solver/shellcmd.py", line 198, in _presolve
    OptSolver._presolve(self, *args, **kwds)
  File "/home/nisenber/Documents/CODE/pyomo/pyomo/opt/base/solvers.py", line 670, in _presolve
    self._convert_problem(args,
  File "/home/nisenber/Documents/CODE/pyomo/pyomo/opt/base/solvers.py", line 740, in _convert_problem
    return convert_problem(args,
  File "/home/nisenber/Documents/CODE/pyomo/pyomo/opt/base/convert.py", line 105, in convert_problem
    problem_files, symbol_map = converter.apply(*tmp, **tmpkw)
  File "/home/nisenber/Documents/CODE/pyomo/pyomo/solvers/plugins/converter/model.py", line 187, in apply
    instance.write(
  File "/home/nisenber/Documents/CODE/pyomo/pyomo/core/base/block.py", line 1705, in write
    (filename, smap) = problem_writer(self,
  File "/home/nisenber/Documents/CODE/pyomo/pyomo/repn/plugins/ampl/ampl_.py", line 370, in __call__
    symbol_map = self._print_model_NL(
  File "/home/nisenber/Documents/CODE/pyomo/pyomo/repn/plugins/ampl/ampl_.py", line 1591, in _print_model_NL
    self._print_nonlinear_terms_NL(
  File "/home/nisenber/Documents/CODE/pyomo/pyomo/repn/plugins/ampl/ampl_.py", line 581, in _print_nonlinear_terms_NL
    self._print_nonlinear_terms_NL(exp.arg(0))
  File "/home/nisenber/Documents/CODE/pyomo/pyomo/repn/plugins/ampl/ampl_.py", line 642, in _print_nonlinear_terms_NL
    raise ValueError(
ValueError: Unsupported expression type (<class 'pyomo.core.expr.numeric_expr.LinearExpression'>) in _print_nonlinear_terms_NL
```

**Comment by natalieisenberg** [comment]
The issue was I was on a different branch of Pyomo, ignore the above!
