### ISSUE TITLE
Issue with new updates in sheet.py

### ISSUE THREAD

**Issue by ZedongPeng** [Pyomo/pyomo#1358]
I merged the up-to-date master branch into my code. There an error with `from pyutilib.excel.spreadsheet import ExcelSpreadsheet, Interfaces` in sheet.py

```
Traceback (most recent call last):
  File "/Users/zedongpeng/.vscode/extensions/ms-python.python-2020.3.69010/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/Users/zedongpeng/.vscode/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/Users/zedongpeng/.vscode/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/Users/zedongpeng/opt/anaconda3/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/Users/zedongpeng/opt/anaconda3/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Users/zedongpeng/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/zedongpeng/Github/pyomo/pyomo/contrib/mindtpy/tests/test_mindtpy.py", line 5, in <module>
    from pyomo.contrib.mindtpy.tests.eight_process_problem import \  File "/Users/zedongpeng/Github/pyomo/pyomo/contrib/mindtpy/tests/eight_process_problem.py", line 28, in <module>    from pyomo.environ import (Binary, ConcreteModel, Constraint, NonNegativeReals,
  File "/Users/zedongpeng/Github/pyomo/pyomo/environ/__init__.py", line 97, in <module>
    _import_packages()
  File "/Users/zedongpeng/Github/pyomo/pyomo/environ/__init__.py", line 84, in _import_packages
    pkg.load()
  File "/Users/zedongpeng/Github/pyomo/pyomo/dataportal/plugins/__init__.py", line 16, in load
    import pyomo.dataportal.plugins.sheet
  File "/Users/zedongpeng/Github/pyomo/pyomo/dataportal/plugins/sheet.py", line 14, in <module>
    from pyutilib.excel.spreadsheet import ExcelSpreadsheet, Interfaces
ImportError: cannot import name 'Interfaces' from 'pyutilib.excel.spreadsheet' (/Users/zedongpeng/opt/anaconda3/lib/python3.7/site-packages/pyutilib/excel/spreadsheet.py)
```
It seems there is no `pyutilib.excel.spreadsheet.Interfaces` in my python3.7 env. Do I need to update pyutilib?
@jsiirola

**Comment by jsiirola** [comment]
Yes.  Pyomo and PyUtilib are developed as a "matched set": if you are going to live on Pyomo master, you should also have PyUtilib master.  Clean installs implicitly force this through `setup.py`.  The `Interfaces` class is available on both master and the most recent release (5.8.0).
