### ISSUE TITLE
No module named 'pyomo.common.dependencies'

### ISSUE THREAD

**Issue by ZedongPeng** [Pyomo/pyomo#1389]
When I merged the latest version of Pyomo/Master, an error is reported.

```
Traceback (most recent call last):
  File "/Users/zedongpeng/Github/pyomo/pyomo/environ/__init__.py", line 70, in _import_packages
    _do_import(pname)
  File "/Users/zedongpeng/Github/pyomo/pyomo/environ/__init__.py", line 16, in _do_import
    importlib.import_module(pkg_name)
  File "/Users/zedongpeng/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/zedongpeng/Github/pyomo/pyomo/common/plugins.py", line 11, in <module>
    from . import download
  File "/Users/zedongpeng/Github/pyomo/pyomo/common/download.py", line 27, in <module>
    from pyomo.common.dependencies import attempt_import
ModuleNotFoundError: No module named 'pyomo.common.dependencies'
```
By the way, the version of Pyutilib in my computer is 5.8.0.

**Comment by qtothec** [comment]
Try clearing *.pyc and __pycache__ files next.

**Comment by qtothec** [comment]
Closing this, since it was likely the result of an earlier wayward merge commit.
