### ISSUE TITLE
Linking PySP stage variables by indexes of stochastic variables

### ISSUE THREAD

**Issue by cecilecro** [Pyomo/pyomo#1398]
I would like to generate the extended form of the following model (contained in a python file named ReferenceModel.py) using the PySP extansion.
The decision variable is a vector of 3 time steps. I want the first time step be in first stage and the following time steps be in second stage.

```
from pyomo.environ import *

# Number of time steps
nb_T = 3
T = list(range(1,nb_T+1))# list of time steps


# Problem data
cost = [0,10,10,10] # Electricity price
p_max = 1000 # Max power


## Create a Concrete Model

model = ConcreteModel("PySP test Concrete")

# Parameters
model.needs = Param(T, within=NonNegativeReals, initialize=0.0, mutable=True)

# Variables
model.p = Var(T, bounds=(0, p_max))

# Constraint
def constraint_needs(model, t):
    return  model.p[t] == model.needs[t] # the power must be equal to the needs
model.constraint_needs = Constraint(T, rule=constraint_needs)


# Stage-specific cost computations
#
def ComputeFirstStageCost_rule(model):
    return model.p[T[0]] * cost[T[0]]
model.FirstStageCost = Expression(rule=ComputeFirstStageCost_rule)

def ComputeSecondStageCost_rule(model):
    return sum(model.p[t] * cost[t] for t in T[1:])
model.SecondStageCost = Expression(rule=ComputeSecondStageCost_rule)


# PySP Auto-generated Objective
#
# minimize: sum of StageCosts
#
def total_cost_rule(model):
    return model.FirstStageCost + model.SecondStageCost
model.Total_Cost_Objective = Objective(rule=total_cost_rule, sense=minimize)


# Number of scenarios
nb_scenarios = 4
              
# Stochastic data              
needs = {}
needs['Scenario1'] = \
    {T[0] : 1, T[1] : 1, T[2] : 1}
needs['Scenario2'] = \
    {T[0] : 1, T[1] : 1, T[2] : 2}
needs['Scenario3'] = \
    {T[0] : 1, T[1] : 1, T[2] : 3}
needs['Scenario4'] = \
    {T[0] : 1, T[1] : 1, T[2] : 4}

def pysp_scenario_tree_model_callback():
    from pyomo.pysp.scenariotree.tree_structure_model \
        import CreateConcreteTwoStageScenarioTreeModel

    st_model = CreateConcreteTwoStageScenarioTreeModel(nb_scenarios)

    first_stage = st_model.Stages.first()
    second_stage = st_model.Stages.last()

    # First Stage
    st_model.StageCost[first_stage] = 'FirstStageCost'
    st_model.StageVariables[first_stage].add('model.p[T[0]]')

    # Second Stage
    st_model.StageCost[second_stage] = 'SecondStageCost'
    st_model.StageVariables[second_stage].add('model.p[T[1:]]')
    return st_model


def pysp_instance_creation_callback(scenario_name, node_names):
    instance = model.clone()
    instance.needs.store_values(needs[scenario_name])
    return instance
```

When I try to generate the extensive form of the problem with the following command :
runef -m ReferenceModel.py, I get the error below:
```
Exception encountered. Scenario tree manager attempting to shut down.
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\runef.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\pyomo\pysp\ef_writer_script.py", line 855, in main
    traceback=options.traceback)
  File "c:\programdata\anaconda3\lib\site-packages\pyomo\pysp\util\misc.py", line 344, in launch_command
    rc = command(options, *cmd_args, **cmd_kwds)
  File "c:\programdata\anaconda3\lib\site-packages\pyomo\pysp\ef_writer_script.py", line 700, in runef
    manager.initialize()
  File "c:\programdata\anaconda3\lib\site-packages\pyomo\pysp\scenariotree\manager.py", line 1391, in initialize
    return super(ScenarioTreeManagerClient, self).initialize(async_call=async_call)
  File "c:\programdata\anaconda3\lib\site-packages\pyomo\pysp\scenariotree\manager.py", line 904, in initialize
    result = self._init(*args, **kwds)
  File "c:\programdata\anaconda3\lib\site-packages\pyomo\pysp\scenariotree\manager.py", line 1595, in _init
    async_handle = self._init_client()
  File "c:\programdata\anaconda3\lib\site-packages\pyomo\pysp\scenariotree\manager.py", line 2190, in _init_client
    create_variable_ids=True)
  File "c:\programdata\anaconda3\lib\site-packages\pyomo\pysp\scenariotree\tree_structure.py", line 1767, in linkInInstances
    initialize_solution_data=initialize_solution_data)
  File "c:\programdata\anaconda3\lib\site-packages\pyomo\pysp\scenariotree\tree_structure.py", line 1881, in populateVariableIndicesAndValues
    initialize_solution_data=initialize_solution_data)
  File "c:\programdata\anaconda3\lib\site-packages\pyomo\pysp\scenariotree\tree_structure.py", line 492, in populateVariableIndicesAndValues
    name_index_to_id_map=name_index_to_id_map)
  File "c:\programdata\anaconda3\lib\site-packages\pyomo\pysp\scenariotree\tree_structure.py", line 284, in updateVariableIndicesAndValues
    scenario_instance.name))
RuntimeError: The component=model.p[T[0]] associated with stage=Stage1 is not present in instance=Scenario1
```
Am I mistaken in writing the model an if so, how to correct it? Thanks

Versions :

- Python 3.7.4
- Pyomo  5.6.8

**Comment by DLWoodruff** [comment]
Here's a quick answer that might lead you to the solution:

model.p[T[0]]

does not really exists by the time PySP is trying to form the EF
because T[0] is not a symbol at the point. I think it might

be 1 in the example you sent. Whatever value has is what PySP will
see. If you want PySP to see the symbol, it has to be a mutable Param,
or you

can refer to the value.  Hope this help a little.

  Dave

**Comment by cecilecro** [comment]
Thank you for pointing out what was wrong !
