### ISSUE TITLE
pprint() fails when Param indexed by non-Pyomo set

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#1509]
```
m = ConcreteModel()
m.fatefulparam = Param([1, 2], initialize={1: -1, 2: 0}, within=set([-1,0,1]))
m.pprint()
```
produces this output:
```
1 Set Declarations
    fatefulparam_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    2 : {1, 2}

1 Param Declarations
Traceback (most recent call last):
  File "set_bug.py", line 13, in <module>
    m.pprint()
  File "/home/esjohn/src/pyomo/pyomo/core/base/component.py", line 500, in pprint
    self.is_constructed(), *self._pprint()
  File "/home/esjohn/src/pyomo/pyomo/core/base/component.py", line 368, in _pprint_base_impl
    _fcn(ostream, _key, _data_dict[_key])
  File "/home/esjohn/src/pyomo/pyomo/core/base/block.py", line 1942, in _pprint_callback
    data._pprint_blockdata_components(ostream)
  File "/home/esjohn/src/pyomo/pyomo/core/base/block.py", line 1673, in _pprint_blockdata_components
    self.component(key).pprint(ostream=indented_ostream)
  File "/home/esjohn/src/pyomo/pyomo/core/base/component.py", line 500, in pprint
    self.is_constructed(), *self._pprint()
  File "/home/esjohn/src/pyomo/pyomo/core/base/param.py", line 960, in _pprint
    ("Domain", self.domain.name),
AttributeError: 'set' object has no attribute 'name'
```
It seems we don't expect the domain of a Param to not be a Pyomo Set. This is true of Vars too but it's actually enforced during construction... Should it be the same for Param?

**Comment by blnicho** [comment]
Looks like this was fixed at some point. This runs successfully on 6.7.0.
