### ISSUE TITLE
BUG: ImportError with PyUtilib 6.0.0

### ISSUE THREAD

**Issue by clyman23** [Pyomo/pyomo#1514]
Found this bug when working with pyomo today (after PyUtilib 6.0.0 was pushed). I noticed suddenly all my pipelines were failing when I hadn't made changes to my code...

You can see the issue if you make a new virtual environment and then install pyomo with pip. Then try importing pyomo. The following should happen:

```python
>>> import pyomo.environ as pe
Traceback (most recent call last):
  File "/Users/conorlyman/modeling/playground/debug/venv/lib/python3.6/site-packages/pyomo/environ/__init__.py", line 69, in _import_packages
    _do_import(pname)
  File "/Users/conorlyman/modeling/playground/debug/venv/lib/python3.6/site-packages/pyomo/environ/__init__.py", line 16, in _do_import
    importlib.import_module(pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/conorlyman/modeling/playground/debug/venv/lib/python3.6/site-packages/pyomo/core/__init__.py", line 11, in <module>
    from pyomo.core.expr import *
  File "/Users/conorlyman/modeling/playground/debug/venv/lib/python3.6/site-packages/pyomo/core/expr/__init__.py", line 36, in <module>
    from .calculus.derivatives import differentiate
  File "/Users/conorlyman/modeling/playground/debug/venv/lib/python3.6/site-packages/pyomo/core/expr/calculus/derivatives.py", line 3, in <module>
    from pyutilib.enum import Enum
  File "/Users/conorlyman/modeling/playground/debug/venv/lib/python3.6/site-packages/pyutilib/enum/__init__.py", line 18, in <module>
    package) that supersedes this library.""")
ImportError: pyutilib.enum has been removed.

Python 3 now has an enum implementation in the standard library (also
available for older Python versions as the third-party enum34 PyPI
package) that supersedes this library.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/conorlyman/modeling/playground/debug/venv/lib/python3.6/site-packages/pyomo/environ/__init__.py", line 97, in <module>
    _import_packages()
  File "/Users/conorlyman/modeling/playground/debug/venv/lib/python3.6/site-packages/pyomo/environ/__init__.py", line 81, in _import_packages
    raise ImportError(msg)
ImportError: pyomo.environ failed to import pyomo.core.plugins:
Original ImportError: pyutilib.enum has been removed.

Python 3 now has an enum implementation in the standard library (also
available for older Python versions as the third-party enum34 PyPI
package) that supersedes this library.
Traceback:
  File "/Users/conorlyman/modeling/playground/debug/venv/lib/python3.6/site-packages/pyomo/environ/__init__.py", line 69, in _import_packages
    _do_import(pname)
  File "/Users/conorlyman/modeling/playground/debug/venv/lib/python3.6/site-packages/pyomo/environ/__init__.py", line 16, in _do_import
    importlib.import_module(pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/conorlyman/modeling/playground/debug/venv/lib/python3.6/site-packages/pyomo/core/__init__.py", line 11, in <module>
    from pyomo.core.expr import *
  File "/Users/conorlyman/modeling/playground/debug/venv/lib/python3.6/site-packages/pyomo/core/expr/__init__.py", line 36, in <module>
    from .calculus.derivatives import differentiate
  File "/Users/conorlyman/modeling/playground/debug/venv/lib/python3.6/site-packages/pyomo/core/expr/calculus/derivatives.py", line 3, in <module>
    from pyutilib.enum import Enum
  File "/Users/conorlyman/modeling/playground/debug/venv/lib/python3.6/site-packages/pyutilib/enum/__init__.py", line 18, in <module>
    package) that supersedes this library.""")
```

Here are the specifications of my virtual environment: 
```python
Package    Version
---------- -------
appdirs    1.4.4  
nose       1.3.7  
pip        20.0.2 
ply        3.11   
Pyomo      5.6.9  
PyUtilib   6.0.0  
setuptools 45.2.0 
six        1.15.0 
wheel      0.34.2
```

Only fix I've found so far is reverting to PyUtilib 5.8.0.

I should specify that this is using Python 3.6.8 on a Mac.

**Comment by jsiirola** [comment]
This is known, and intentional.  #1506 resolved the dependency problem.  We are processing a new pyomo release (5.7), which should show up on PyPI / conda-forge either this afternoon or Monday.
