### ISSUE TITLE
Pyomo 5.6.9 has conflict with PyUtilib 6.0.0

### ISSUE THREAD

**Issue by sneaxiy** [Pyomo/pyomo#1525]
PyUtilib 6.0.0 has been released on June 20, 2020. Pyomo 5.6.9 requires PyUtilib>=5.8.0 (see [here](https://github.com/Pyomo/pyomo/blob/5.6.9/setup.py#L41)). 

But it means that Pymo 5.6.9 does not work with PyUtilib 6.0.0. There would be an error when `import pyomo.environ`:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyomo/environ/__init__.py", line 69, in _import_packages
    _do_import(pname)
  File "/usr/local/lib/python3.6/dist-packages/pyomo/environ/__init__.py", line 16, in _do_import
    importlib.import_module(pkg_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/pyomo/core/__init__.py", line 11, in <module>
    from pyomo.core.expr import *
  File "/usr/local/lib/python3.6/dist-packages/pyomo/core/expr/__init__.py", line 36, in <module>
    from .calculus.derivatives import differentiate
  File "/usr/local/lib/python3.6/dist-packages/pyomo/core/expr/calculus/derivatives.py", line 3, in <module>
    from pyutilib.enum import Enum
  File "/usr/local/lib/python3.6/dist-packages/pyutilib/enum/__init__.py", line 18, in <module>
    package) that supersedes this library.""")
ImportError: pyutilib.enum has been removed.
```

**Comment by blnicho** [comment]
Please update to Pyomo 5.7.0, it was just released a few hours ago and it looks like you upgraded PyUtilib in the middle of our release process.

**Comment by harmon** [comment]
We just ran into this as well. Is there a reason this project is using `~=` operators when defining the install_requires? You should at least lock down your deps to the same major version. It would prevent issues like this. If you had `PyUtilib~=5.7`, then it wouldn't try and upgrade to a potentially breaking major version.

**Comment by blnicho** [comment]
@harmon thanks for the suggestion. Historically PyUtilib and Pyomo have been released together in matched sets which has led to issues with users having incompatible versions. We are working on getting rid of the PyUtilib dependency as a permanent fix to this problem.

**Comment by harmon** [comment]
@blnicho Sure, but it's still usually good practice to have loose dependencies on a particular **major** version of your underlying libraries (assuming they can be trusted to follow good SemVer practices):
```
install_requires=[
    'PyUtilib>=6.0.1.dev0',
    'enum34;python_version<"3.4"',
    'ply',                             <== This has no version specified at all, so which version is known to 
                                           work with Pyomo?
    'six>=1.4',                        <== What happens if six v2.0 comes out and changes it's API?
],
```

This would be an ideal setup:
```
install_requires=[
    'PyUtilib~=6.0',              <== Won't upgrade to v7.x
    'enum34~=1.1;python_version<"3.4"',  <== Won't upgrade to v2.x
    'ply~=3.0',                          <== Won't upgrade to v4.x
    'six~=1.4',                          <== Won't upgrade to v2.x
],
```

Anyway, just a suggestion based on my own experience dealing with lots of dependencies.

Thanks for the great library, btw!
