### ISSUE TITLE
Substituting python native numeric type using clone_expression breaks polynomial_degree

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#167]
The main issue here is that I am substituting an `int`/`float` in where a `Var` used to be: `clone_expression(expr, substitute={id(var): value(var)}`. Later, during presolve, the `polynomial_degree()` call on `_PowExpression` expects elements of `_args` to be expressions or `NumericValue` (I think). This assumption fails because `value(var)` put an `int` or `float` there.

Example:
```
from pyomo.environ import (ConcreteModel, Var, NonNegativeReals, Binary,
                           Objective, minimize, value, Constraint)
from pyomo.opt import SolverFactory
from pyomo.core.base.expr_common import clone_expression

m = ConcreteModel()
m.x = Var(domain=NonNegativeReals, bounds=(2, None))
m.y = Var(domain=Binary)
m.bomp = Var(initialize=2)
m.o = Objective(expr=m.x, sense=minimize)
sub = {id(m.bomp): value(m.bomp)}
m.c = Constraint(expr=8.36744363177e-10 * (m.y - (m.bomp)**2.0) +
                 0.999999996655 * (-2.0 + m.x) <= 0)
m.c.deactivate()
m.c2 = Constraint(expr=clone_expression(m.c.body, substitute=sub) <= 0)
SolverFactory('gurobi').solve(m, tee=True)
```
Stack trace:
```
Traceback (most recent call last):
  File "test2.py", line 17, in <module>
    SolverFactory('gurobi').solve(m, tee=True)
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/opt/base/solvers.py", line 597, in solve
    self._presolve(*args, **kwds)
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/solvers/plugins/solvers/GUROBI.py", line 209, in _presolve
    ILMLicensedSystemCallSolver._presolve(self, *args, **kwds)
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/opt/solver/shellcmd.py", line 196, in _presolve
    OptSolver._presolve(self, *args, **kwds)
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/opt/base/solvers.py", line 693, in _presolve
    **kwds)
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/opt/base/solvers.py", line 761, in _convert_problem
    **kwds)
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/opt/base/convert.py", line 110, in convert_problem
    problem_files, symbol_map = converter.apply(*tmp, **tmpkw)
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/solvers/plugins/converter/model.py", line 96, in apply
    io_options=io_options)
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/core/base/block.py", line 1647, in write
    io_options)
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/repn/plugins/cpxlp.py", line 170, in __call__
    include_all_variable_bounds=include_all_variable_bounds)
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/repn/plugins/cpxlp.py", line 655, in _print_model_LP
    for constraint_data, canonical_repn in yield_all_constraints():
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/repn/plugins/cpxlp.py", line 635, in constraint_generator
    canonical_repn = generate_canonical_repn(constraint_data.body)
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/repn/canonical_repn.py", line 1070, in generate_canonical_repn
    return coopr3_generate_canonical_repn(exp, idMap, compute_values)
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/repn/canonical_repn.py", line 805, in coopr3_generate_canonical_repn
    degree = exp.polynomial_degree()
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/core/kernel/expr_coopr3.py", line 412, in polynomial_degree
    x_degree = x.polynomial_degree()
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/core/kernel/expr_coopr3.py", line 412, in polynomial_degree
    x_degree = x.polynomial_degree()
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/core/kernel/expr_coopr3.py", line 341, in polynomial_degree
    if self._args[0].is_fixed():
AttributeError: 'int' object has no attribute 'is_fixed'
```

**Comment by qtothec** [comment]
This was fixed by #169
