### ISSUE TITLE
Unicode Decode Error

### ISSUE THREAD

**Issue by sk-surya** [Pyomo/pyomo#1855]
When trying the following command on Windows 10 cmd:
```shell_session
pyomo help --solvers
```

I get the following error.
```shell_session
Traceback (most recent call last):
  File "F:\MyPrograms\anaconda3\Scripts\pyomo-script.py", line 10, in <module>
    sys.exit(main())
  File "F:\MyPrograms\anaconda3\lib\site-packages\pyomo\scripting\pyomo_main.py", line 82, in main
    retval = _options.func(_options)
  File "F:\MyPrograms\anaconda3\lib\site-packages\pyomo\scripting\driver_help.py", line 447, in help_exec
    help_solvers()
  File "F:\MyPrograms\anaconda3\lib\site-packages\pyomo\scripting\driver_help.py", line 316, in help_solvers
    ver = opt.version()
  File "F:\MyPrograms\anaconda3\lib\site-packages\pyomo\opt\base\solvers.py", line 427, in version
    self._version = self._get_version()
  File "F:\MyPrograms\anaconda3\lib\site-packages\pyomo\solvers\plugins\solvers\IPOPT.py", line 81, in _get_version
    results = run( [solver_exec,"-v"], timelimit=1 )
  File "F:\MyPrograms\anaconda3\lib\site-packages\pyutilib\subprocess\processmngr.py", line 715, in run_command
    output = "".join(tmpfile.readlines())
  File "F:\MyPrograms\anaconda3\lib\tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
  File "F:\MyPrograms\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 42: character maps to <undefined>
```

Pyomo version 5.7.3

**Comment by sk-surya** [comment]
I had an existing ipopt.exe installation.

On cmd, 
```shell_session
ipopt.exe -v
```
gives
```shell_session
Ipopt 3.8.1 (Microsoft cl 15.00.21022.08 für 80x86), ASL(20100130)
```
Removing ipopt.exe from path fixes the issue for me for now.
