### ISSUE TITLE
find_component raises error if index has a . in it

### ISSUE THREAD

**Issue by vova292** [Pyomo/pyomo#1857]
We get an error if we run the following code. It seems to be related to the `.` in the index name

```
import pyomo.environ as pyo
m1 = pyo.ConcreteModel()
m1.s1 = pyo.Set(initialize=['a.b', 'a.c'])
m1.v1 = pyo.Var(m1.s1)
m1.find_component(m1.v1['a.b'].name)


Traceback (most recent call last):
  File "/home/shabroz/.virtualenvs/empc/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-b90f6fa6fd93>", line 1, in <module>
    m1.find_component(m1.v1['a.b'].name)
  File "/home/shabroz/.virtualenvs/empc/lib/python3.7/site-packages/pyomo/core/base/block.py", line 907, in find_component
    return ComponentUID(label_or_component).find_component_on(self)
  File "/home/shabroz/.virtualenvs/empc/lib/python3.7/site-packages/pyomo/core/base/componentuid.py", line 101, in __init__
    self._cids = tuple(self._parse_cuid_v2(component))
  File "/home/shabroz/.virtualenvs/empc/lib/python3.7/site-packages/pyomo/core/base/componentuid.py", line 476, in _parse_cuid_v2
    assert not idx_stack
AssertionError
```

**Comment by blnicho** [comment]
@vova292 could you give a little more context on your use-case? Is there a reason you need to use the name in your call to `find_component` instead of doing something like the following?
 
`m1.find_component(m1.v1['a.b'])`

**Comment by Robbybp** [comment]
If you need to perform the `find_component` call on something hashable, I believe you could use
```python
name = str(pyo.ComponentUID(m1.v1['a.b']))
m1.find_component(name)
```

**Comment by vova292** [comment]
The broader usecase is to try and get external data like real world process measurements or an initial state of the model into the model variables. The data could be coming from a database or a network. We read the latest data available and update the variable by finding it by name and setting the value
