### ISSUE TITLE
Bug when indexing components by both a Set and an indexed Set

### ISSUE THREAD

**Issue by blnicho** [Pyomo/pyomo#191]
Consider the following model:

    m = ConcreteModel()
    m.s = Set(['s1','s2'], initialize=[1,2,3])
    m.s2 = Set(initialize=['a','b','c'])

The following works

    m.p = Param(m.s['s1'], initialize=10)
    temp = m.s['s1'] * m.s2
    m.v = Var(temp, initialize=5)

But trying to get the cross product directly in the component declaration fails with different unhelpful error messages depending on the ordering of the sets:

    >>> m.v_1 = Var(m.s['s1'], m.s2, initialize=10)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/blnicho/Research/pyomo/pyomo/core/base/var.py", line 471, in __init__
        IndexedComponent.__init__(self, *args, **kwd)
      File "/home/blnicho/Research/pyomo/pyomo/core/base/indexed_component.py", line 308, in __init__
        self._index = tmp[0].cross(*tmp[1:])
    AttributeError: '_IndexedSetData' object has no attribute 'cross'
    >>> m.v_1 = Var(m.s2, m.s['s1'], initialize=10)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/blnicho/Research/pyomo/pyomo/core/base/block.py", line 542, in __setattr__
        self.add_component(name, val)
      File "/home/blnicho/Research/pyomo/pyomo/core/base/block.py", line 870, in add_component
        self._add_temporary_set(val)
      File "/home/blnicho/Research/pyomo/pyomo/core/base/block.py", line 686, in _add_temporary_set
        if tset._name == "_unknown_":
    AttributeError: '_IndexedSetData' object has no attribute '_name'

This bug is possibly related to #43

**Comment by blnicho** [comment]
This has been fixed with the Set rewrite.
