### ISSUE TITLE
A Var indexed by a union involving an empty set has unknown dimension, breaking Reference

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#1928]
## Summary

If you index a Var with a set that was constructed using a union where one of the sets was empty, then later you cannot create a Reference to this IndexedVar, I think because it doesn't know its dimension.

### Steps to reproduce the issue

```
from pyomo.environ import *

m = ConcreteModel()

m.thinga = Set(initialize=['e1', 'e2', 'e3'])
m.thingb = Set(initialize=[])

m.v = Var(m.thinga | m.thingb, domain=Binary)
print(m.v.dim()) 

m.ref = Reference(m.v)
```

### Error Message
`m.v.dim()` is `pyomo.core.base.set.UnknownSetDimen`.
Stack trace from creating the Reference is:
```
Traceback (most recent call last):
  File "huh.py", line 27, in <module>
    m.ref = Reference(m.v)
  File "/home/esjohn/src/pyomo/pyomo/core/base/reference.py", line 618, in Reference
    reference = reference[...]
  File "/home/esjohn/src/pyomo/pyomo/core/base/indexed_component.py", line 411, in __getitem__
    validated_index = self._validate_index(index)
  File "/home/esjohn/src/pyomo/pyomo/core/base/indexed_component.py", line 559, in _validate_index
    return self._processUnhashableIndex(idx)
  File "/home/esjohn/src/pyomo/pyomo/core/base/indexed_component.py", line 696, in _processUnhashableIndex
    elif ellipsis is not None and slice_dim < set_dim:
TypeError: '<' not supported between instances of 'int' and 'type'
```
(So `set_dim` is `pyomo.core.base.set.UnknownSetDimen`, causing the `TypeError`).

### Information on your system

Pyomo version: main branch
Python version: 3.6.5
Operating system: linux
How Pyomo was installed (PyPI, conda, source): source
Solver (if applicable):

**Comment by Robbybp** [comment]
I've ran into this issue before. I forget what workaround I used, but
```python
m.thingb = Set(initialize=[], dimen=1)
```
might be a viable.
