### ISSUE TITLE
Reference to empty IndexedComponent indexed by non-finite set

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#2039]
## Summary

If you make a Reference to an IndexedVar indexed by NonNegativeIntegers, but the Var doesn't have any VarDatas yet, then the model can't pprint.

### Steps to reproduce the issue

```
from pyomo.environ import *

m = ConcreteModel()
m.v = Var(NonNegativeIntegers, dense=False)

m.ref = Reference(m.v)
m.pprint()
```

### Error Message

```
1 Var Declarations
    v : Size=0, Index=NonNegativeIntegers
        Key : Lower : Value : Upper : Fixed : Stale : Domain

1 IndexedComponent Declarations
    ref : Size=0, Index=ref_index
        Key : Object

1 SetOf Declarations
Traceback (most recent call last):
  File "pprint_bug.py", line 7, in <module>
    m.pprint()
  File "/home/esjohn/src/pyomo/pyomo/core/base/component.py", line 505, in pprint
    self.is_constructed(), *self._pprint()
  File "/home/esjohn/src/pyomo/pyomo/core/base/component.py", line 359, in _pprint_base_impl
    _fcn(ostream, _key, _data_dict[_key])
  File "/home/esjohn/src/pyomo/pyomo/core/base/block.py", line 1992, in _pprint_callback
    data._pprint_blockdata_components(ostream)
  File "/home/esjohn/src/pyomo/pyomo/core/base/block.py", line 1696, in _pprint_blockdata_components
    self.component(key).pprint(ostream=indented_ostream)
  File "/home/esjohn/src/pyomo/pyomo/core/base/component.py", line 505, in pprint
    self.is_constructed(), *self._pprint()
  File "/home/esjohn/src/pyomo/pyomo/core/base/set.py", line 2354, in _pprint
    [("Dimen", self.dimen),
  File "/home/esjohn/src/pyomo/pyomo/core/base/set.py", line 2330, in dimen
    _iter = iter(self)
  File "/home/esjohn/src/pyomo/pyomo/core/base/set.py", line 1137, in __iter__
    return self._iter_impl()
  File "/home/esjohn/src/pyomo/pyomo/core/base/set.py", line 2311, in _iter_impl
    return iter(self._ref)
  File "/home/esjohn/src/pyomo/pyomo/core/base/reference.py", line 393, in __iter__
    return self._slice.index_wildcard_keys()
  File "/home/esjohn/src/pyomo/pyomo/core/base/indexed_component_slice.py", line 263, in index_wildcard_keys
    _iter = _IndexedComponent_slice_iter(self, iter_over_index=True)
  File "/home/esjohn/src/pyomo/pyomo/core/base/indexed_component_slice.py", line 439, in __init__
    *call_stack[0][1], iter_over_index=self._iter_over_index)
  File "/home/esjohn/src/pyomo/pyomo/core/base/indexed_component_slice.py", line 329, in __init__
    self.component_iter = component.index_set().__iter__()
  File "/home/esjohn/src/pyomo/pyomo/core/base/set.py", line 508, in __iter__
    "is not iterable)" % (self.__class__.__name__, self.name))
TypeError: 'GlobalSet' object is not iterable (non-finite Set 'NonNegativeIntegers' is not iterable)
```

### Information on your system

Pyomo version: main branch
Python version: 3.6.5
Operating system: linux
How Pyomo was installed (PyPI, conda, source): source
Solver (if applicable):

**Comment by Robbybp** [comment]
Looks like a bug in how we identify a reference's index set. Probably can avoid iterating over the slice if a component is provided, as the component presumably already knows its own index set. A quick workaround is probably to just pre-populate `slice_idx` if a component is provided, i.e.
```python
    elif isinstance(reference, Component):
        reference = reference[...]
        _data = _ReferenceDict(reference)
        _iter = iter(reference)
        slice_idx = _identify_wildcard_sets(_iter._iter_stack, []) 
        index = None
```
in the reference argument processing around line 620 of reference.py.
