### ISSUE TITLE
stdout and stderr ordering issues when streaming solver output

### ISSUE THREAD

**Issue by carldlaird** [Pyomo/pyomo#21]
I believe that the order of stdout and stderr is not preserved when streaming solver output.

Details:
I have attached fm7.py. During solution of this problem, IPOPT (or rather ASL) encounters an evaluation error (sqrt of a negative number). The option "halt_on_ampl_error" is set to "yes", therefore there is an error printed to the console that indicates the problematic expression/constraint (from an ASL standpoint).

However, this error does not appear at the end of the console output (when it actually occurred), but rather up in the middle of the output, leading to confusion of where this error occurred in the solution process. 

This can be reproduced if IPOPT is installed (with MUMPS) using the following command:
$ python fm7.py
My output from this command is stored in fm7.pyomo.out.

If we run the ".nl" file manually with IPOPT, we see the correct ordering. The details of the error are printed at the end (along with the correct iteration where the error appeared). This can be reproduced with the following command:
$ ipopt path/to/fm7.nl halt_on_ampl_error=yes
My output from this command is stored in fm7.ipopt_nl.out

While ordering of stdout and stderr to the screen may not be guaranteed, I suspect that IPOPT manually flushes the stdout buffer to ensure the correct order. This is lost in Pyomo.

[ticket.zip](https://github.com/Pyomo/pyomo/files/415438/ticket.zip)

**Comment by jsiirola** [comment]
I am pretty sure this is a PyUtilib issue and not a Pyomo issue.  The trick is that the output handling and redirection in pyutilib.subprocess is managed by separate threads.  There is really no way to guarantee output ordering even when IPOPT flushes stdout (the flush call only exists in the IPOPT process and doesn't trigger anything in the Python process).  The place to look in PyUtilib are the `_stream_reader`, `_merged_reader`, and `_pseudo_merged_reader` functions in https://github.com/PyUtilib/pyutilib/blob/master/pyutilib/subprocess/processmngr.py

**Comment by mrmundt** [comment]
@jsiirola - Have we "resolved" this issue by moving to `TeeStream`?

**Comment by jsiirola** [comment]
I can confirm that on Pyomo/main the output is
```
Solver log file: '/tmp/tmp8p90dax0_ipopt.log'
Solver solution file: '/tmp/tmpjoexh9r0.pyomo.sol'
Solver problem files: ('/tmp/tmpjoexh9r0.pyomo.nl',)
Ipopt 3.13.2: halt_on_ampl_error=yes


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of Ipopt was compiled from source code available at
    https://github.com/IDAES/Ipopt as part of the Institute for the Design of
    Advanced Energy Systems Process Systems Engineering Framework (IDAES PSE
    Framework) Copyright (c) 2018-2019. See https://github.com/IDAES/idaes-pse.

This version of Ipopt was compiled using HSL, a collection of Fortran codes
    for large-scale scientific computation.  All technical papers, sales and
    publicity material resulting from use of the HSL codes within IPOPT must
    contain the following acknowledgement:
        HSL, a collection of Fortran codes for large-scale scientific
        computation. See http://www.hsl.rl.ac.uk.
******************************************************************************

This is Ipopt version 3.13.2, running with linear solver ma27.

Number of nonzeros in equality constraint Jacobian...:        2
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        2

Total number of variables............................:        2
                     variables with only lower bounds:        1
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        1
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  4.0920100e+01 3.00e+00 8.92e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  1.3964766e+00 9.81e-01 4.57e+00  -1.0 4.20e+00    -  1.00e+00 9.43e-01f  1
   2  1.3265288e+00 4.58e-01 9.56e+00  -1.0 3.54e-01   2.0 1.31e-01 1.00e+00f  1
   3  3.2528786e-01 1.23e-02 1.25e+00  -1.0 5.70e-01    -  1.00e+00 1.00e+00f  1
   4  4.9701812e-03 7.82e-02 1.36e-01  -1.0 3.78e-01    -  1.00e+00 1.00e+00F  1
   5  6.0628408e-03 4.53e-02 1.66e+00  -2.5 2.08e-02    -  1.00e+00 1.00e+00h  1
   6  6.7063949e-03 4.53e-02 2.24e+00  -2.5 1.05e+00    -  1.53e-02 3.91e-03h  9
   7  7.6973110e-03 1.67e-02 5.10e-01  -2.5 6.16e-03   1.5 1.00e+00 1.00e+00h  1
   8  3.5855462e-03 1.09e-03 2.51e-01  -2.5 2.81e-02    -  1.00e+00 1.00e+00h  1
   9  3.0456986e-03 1.24e-04 1.10e-03  -2.5 4.78e-03    -  1.00e+00 1.00e+00h  1
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
  10  9.2960387e-04 1.58e-02 1.21e+00  -3.8 2.59e-02    -  1.00e+00 1.00e+00h  1
  11  2.2722219e-04 1.18e-04 1.42e-01  -3.8 1.75e-02    -  1.00e+00 1.00e+00h  1
  12  2.4804811e-04 4.21e-05 4.38e-03  -3.8 8.99e-04    -  1.00e+00 1.00e+00h  1
  13  2.5041988e-04 8.02e-07 1.04e-04  -3.8 9.89e-05    -  1.00e+00 1.00e+00h  1
  14  1.3928326e-04 4.89e-03 3.54e+00  -5.7 6.12e-03    -  1.00e+00 1.00e+00h  1
  15  1.6721345e-04 3.66e-03 4.16e+00  -5.7 1.95e-03   1.0 1.01e-01 1.00e+00h  1
  16  1.7756299e-04 1.12e-03 2.28e+00  -5.7 6.51e-04   1.5 1.00e+00 1.00e+00h  1
  17  1.5169810e-04 1.68e-05 1.58e-01  -5.7 1.61e-03   1.0 1.00e+00 1.00e+00h  1
Error evaluating "var =" definition -1: can't evaluate sqrt(-9.90312e-09).
ERROR: Solver (ipopt) returned non-zero return code (1)
ERROR: See the solver log above for diagnostic information.
Traceback (most recent call last):
  File "fm7.py", line 18, in <module>
    solver.solve(model, tee=True, keepfiles=True)
  File "[...]/pyomo/opt/base/solvers.py", line 598, in solve
    "Solver (%s) did not exit normally" % self.name)
pyomo.common.errors.ApplicationError: Solver (ipopt) did not exit normally
```

Which is inline with that @carldlaird was expecting.  I believe that we can close this issue.
