### ISSUE TITLE
Cannot extend indexed port

### ISSUE THREAD

**Issue by dallan-keylogic** [Pyomo/pyomo#2119]
## Summary

While creating a minimal example to show a nonintuitive bug/"feature" of `pyomo.network.SequentialDecomposition`, I found that ports on indexed blocks cannot be extended.

### Steps to reproduce the issue

```
#indexed_port_fail.py
from pyomo.environ import ConcreteModel, Block, Var
from pyomo.network import Port

m = ConcreteModel()
m.blk = Block()

m.blk.sub_blks = Block(range(2))

m.blk.sub_blks[0].x = Var(bounds=(0,1), initialize = 0)
m.blk.sub_blks[0].inlet = Port({'x':m.blk.sub_blks[0].x})

m.blk.inlet = Port(extends = m.blk.sub_blks[0].inlet)

```

```console
runfile('[REDACTED]/indexed_port_fail.py', wdir='[REDACTED]')
ERROR: Constructing component 'blk.inlet' from data=None failed:
    AttributeError: 'IndexedPort' object has no attribute 'vars'
Traceback (most recent call last):

  File "[REDACTED]\indexed_port_fail.py", line 19, in <module>
    m.blk.inlet = Port(extends = m.blk.sub_blks[0].inlet)

  File "[REDACTED]\miniconda3\envs\idaes\lib\site-packages\pyomo\core\base\block.py", line 541, in __setattr__
    self.add_component(name, val)

  File "[REDACTED]\miniconda3\envs\idaes\lib\site-packages\pyomo\core\base\block.py", line 1086, in add_component
    val.construct(data)

  File "[REDACTED]\miniconda3\envs\idaes\lib\site-packages\pyomo\network\port.py", line 365, in construct
    self._initialize_members([None])

  File "[REDACTED]\miniconda3\envs\idaes\lib\site-packages\pyomo\network\port.py", line 381, in _initialize_members
    for key, val in self._extends.vars.items():

AttributeError: 'IndexedPort' object has no attribute 'vars'
```

### Information on your system

Pyomo version: 6.1.2
Python version: 3.9.6 (default, Aug 18 2021, 15:44:49) [MSC v.1916 64 bit (AMD64)]
Operating system: Windows 10
How Pyomo was installed: Either Pip or Conda

**Comment by jsiirola** [comment]
This is intentional.  You are defining an `IndexedPort` and not a `Port`.  As an Indexed "thing" is a container of things, and not an actual thing, it does not support the full API of the things it holds.

My guess is that you are forgetting the `initialize=` keyword argument in your `inlet` declaration.
