### ISSUE TITLE
Can't solve subblock with gurobi_direct

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#2130]
## Summary

Hopefully this isn't a duplicate issue, but it is not possible to solve a ScalarBlock with `gurobi_direct`.

### Steps to reproduce the issue

```
from pyomo.environ import *

m = ConcreteModel()
m.b = Block()
m.b.v = Var(bounds=(0,10))
m.b.c = Constraint(expr=m.b.v >= 2)
m.b.obj = Objective(expr=m.b.v)

results = SolverFactory('gurobi_direct').solve(m.b)
```

### Error Message

```
Traceback (most recent call last):
  File "solve_scalar_block.py", line 9, in <module>
    results = SolverFactory('gurobi_direct').solve(m.b)
  File "/home/esjohn/src/pyomo/pyomo/solvers/plugins/solvers/direct_solver.py", line 119, in solve
    self._presolve(*args, **kwds)
  File "/home/esjohn/src/pyomo/pyomo/solvers/plugins/solvers/direct_solver.py", line 64, in _presolve
    DirectOrPersistentSolver._presolve(self, **kwds)
  File "/home/esjohn/src/pyomo/pyomo/solvers/plugins/solvers/direct_or_persistent_solver.py", line 149, in _presolve
    self._pyomo_model.solutions.add_symbol_map(self._symbol_map)
  File "/home/esjohn/src/pyomo/pyomo/core/base/block.py", line 522, in __getattr__
    % (self.__class__.__name__, val))
AttributeError: 'ScalarBlock' object has no attribute 'solutions'
```

### Information on your system

Pyomo version: main
Python version: 3.6.5
Operating system: linux
How Pyomo was installed (PyPI, conda, source): source
Solver (if applicable): Gurobi

**Comment by michaelbynum** [comment]
This will work if you use `save_results=False` in the call to `solve`.

**Comment by michaelbynum** [comment]
I think this can be closed? This does work with the above keyword argument. This will also be less of an issue in `contrib.solver`.

**Comment by emma58** [comment]
Do we test it in `contrib.solver`? I don't think it should require a keyword argument in the long run.

**Comment by michaelbynum** [comment]
Yes, we have a test here: https://github.com/Pyomo/pyomo/blob/52a29ae82b39e2e6bcefe31ab622ba1dbe7da8f5/pyomo/contrib/solver/tests/solvers/test_solvers.py#L2028

**Comment by emma58** [comment]
I don't think that's quite the same thing though--in the example above the variables were on the sub-block being solved, so that must not have been the issue.

**Comment by michaelbynum** [comment]
Sorry - I was getting issues mixed up...

**Comment by michaelbynum** [comment]
The problem here is that `model.solutions.load_from(results)` relies on the fact that `ConcreteModel` has a `solutions` attribute that does not exist on `BlockData`. However, we don't use `model.solutions.load_from` at all in `contrib.solver`, so the problem goes away.
