### ISSUE TITLE
Cannot make Reference to a ConstraintData from a ConstraintList

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#2333]
## Summary

References to ConstraintDatas in ConstraintLists die on a TypeError. ConstraintDatas of other IndexedConstraints seem okay.

### Steps to reproduce the issue

```
from pyomo.environ import *

m = ConcreteModel()
m.x = Var()
m.cl = ConstraintList()
m.c2 = Constraint(PositiveIntegers)

m.cl.add(m.x >= 0)
m.c2[1] = m.x >= 0
m.cl.add(m.x <= 1)
m.c2[2] = m.x <= 1

thing1 = Reference(m.c2[2]) # this one is fine
thing2 = Reference(m.cl[2]) # this gives the TypeError below
```

### Error Message

```
Traceback (most recent call last):
  File "reference_to_constraintListData.py", line 18, in <module>
    thing2 = Reference(m.cl[2])
  File "/home/esjohn/src/pyomo/pyomo/core/base/reference.py", line 644, in Reference
    comp = _parent.__class__(SetOf(UnindexedComponent_set))
TypeError: __init__() takes 1 positional argument but 2 were given
```

### Information on your system

Pyomo version: main
Python version: 3.8
Operating system: linux
How Pyomo was installed (PyPI, conda, source): source
Solver (if applicable):

**Comment by emma58** [comment]
This is resolved, not sure by what.
