### ISSUE TITLE
APPSI doesn't solve GDP model with AutoLinkedBinaryVars

### ISSUE THREAD

**Issue by emma58** [Pyomo/pyomo#2355]
## Summary

The APPSI Gurobi solver dies on a KeyError if I give it a transformedto-a-MIP GDP. It looks like  the `AutoLinkedBooleanVar` indicator variables take it by surprise?

### Steps to reproduce the issue

```
from pyomo.contrib.appsi.solvers.gurobi import Gurobi
from pyomo.environ import *
from pyomo.gdp import *

m = ConcreteModel()
m.x = Var(bounds=(-5, 5))
m.disjunction = Disjunction(expr=[[m.x == 2], [m.x >= -1]])
m.obj = Objective(expr=m.x)

TransformationFactory('gdp.bigm').apply_to(m)

Gurobi().solve(m)
```

### Error Message

```
Traceback (most recent call last):
  File "appsi_and_gdp.py", line 12, in <module>
    Gurobi().solve(m)
  File "/home/esjohn/src/pyomo/pyomo/contrib/appsi/solvers/gurobi.py", line 340, in solve
    self.set_instance(model)
  File "/home/esjohn/src/pyomo/pyomo/contrib/appsi/solvers/gurobi.py", line 451, in set_instance
    self.add_block(model)
  File "/home/esjohn/src/pyomo/pyomo/contrib/appsi/base.py", line 883, in add_block
    self.add_constraints([con for con in block.component_data_objects(Constraint, descend_into=True,
  File "/home/esjohn/src/pyomo/pyomo/contrib/appsi/base.py", line 809, in add_constraints
    named_exprs, variables, fixed_vars, external_functions = cmodel.prep_for_repn(con.body, expr_types)
KeyError: <class 'pyomo.gdp.disjunct.AutoLinkedBinaryVar'>
```

### Information on your system

Pyomo version: main
Python version: 3.8
Operating system: linux
How Pyomo was installed (PyPI, conda, source): source
Solver (if applicable): Gurobi 9.1.2

**Comment by michaelbynum** [comment]
Thanks. I'll get this fixed.

**Comment by emma58** [comment]
Thank you! :)
