### ISSUE TITLE
appsi_gurobi    gurobipy.GurobiError: Unable to retrieve attribute 'Pi'

### ISSUE THREAD

**Issue by ZedongPeng** [Pyomo/pyomo#2372]
## Summary

I am using  `SolverFactory('appsi_gurobi')` to solve a MILP and get its dual.
An error is reported `gurobipy.GurobiError: Unable to retrieve attribute 'Pi'`.
How can I fix it? @michaelbynum 
`appsi_cplex` does not support getting duals for MILP. Is this also applied to `appsi_gurobi`?

### Steps to reproduce the issue

```
# example.py
from pyomo.environ import *
from pyomo.contrib.mindtpy.tests.eight_process_problem import EightProcessFlowsheet

model = EightProcessFlowsheet()
for constr in model.component_data_objects(Constraint):
    if constr.body.polynomial_degree() not in {0, 1}:
        constr.deactivate()
model.dual = Suffix(direction=Suffix.IMPORT)
opt = SolverFactory('appsi_gurobi')
res = opt.solve(model, tee=True)
print(res)
```

### Error Message

```console
$ # Output message here, including entire stack trace, if available

Gurobi Optimizer version 9.0.0 build v9.0.0rc2 (mac64)
Optimize a model with 26 rows, 32 columns and 66 nonzeros
Model fingerprint: 0x68b3ce51
Variable types: 24 continuous, 8 integer (8 binary)
Coefficient statistics:
  Matrix range     [4e-01, 1e+01]
  Objective range  [1e+00, 8e+01]
  Bounds range     [1e+00, 1e+01]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective -523.0000000
Presolve removed 20 rows and 26 columns
Presolve time: 0.00s
Presolved: 6 rows, 6 columns, 17 nonzeros
Found heuristic solution: objective -1973.000000
Variable types: 4 continuous, 2 integer (2 binary)

Explored 0 nodes (0 simplex iterations) in 0.00 seconds
Thread count was 12 (of 12 available processors)

Solution count 2: -1973 -523 
No other solutions better than -1973

Optimal solution found (tolerance 1.00e-04)
Best objective -1.973000000000e+03, best bound -1.973000000000e+03, gap 0.0000%
Traceback (most recent call last):
  File "/Users/zedongpeng/Github/pyomo-MINLP-benchmarking/test.py", line 79, in <module>
    res = opt.solve(model, tee=True)
  File "/Users/zedongpeng/Github/pyomo/pyomo/contrib/appsi/base.py", line 1264, in solve
    for c, val in results.solution_loader.get_duals().items():
  File "/Users/zedongpeng/Github/pyomo/pyomo/contrib/appsi/base.py", line 695, in get_duals
    return self._solver.get_duals(cons_to_load=cons_to_load)
  File "/Users/zedongpeng/Github/pyomo/pyomo/contrib/appsi/solvers/gurobi.py", line 900, in get_duals
    linear_vals = self._solver_model.getAttr("Pi", linear_cons_to_load)
  File "model.pxi", line 1774, in gurobipy.Model.getAttr
  File "attrutil.pxi", line 148, in gurobipy.__gettypedattrlist
gurobipy.GurobiError: Unable to retrieve attribute 'Pi'
```

### Information on your system

Pyomo version: 6.4.1.dev0
Python version: Python 3.7.7
Operating system: MacOS 
How Pyomo was installed (PyPI, conda, source):
Solver (if applicable): appsi_gurobi

**Comment by michaelbynum** [comment]
To the best of my knowledge, these solvers (both Cplex and Gurobi) do not provide duals for mixed-integer problems, regardless of the Pyomo interface.
