### ISSUE TITLE
Error with CPLEX 22.1.0.0

### ISSUE THREAD

**Issue by ernestoar** [Pyomo/pyomo#2376]
## Summary

I am facing a solution parsing error when calling CPLEX to solve a Pyomo model. This seems an issue that is resurfacing this time on CPLEX version 22.1.0.0

### Example code

```
# example.py
import pyomo.environ as pyo
model = pyo.ConcreteModel()
model.x = pyo.Var([1, 2], domain=pyo.NonNegativeReals)
model.OBJ = pyo.Objective(expr=2 * model.x[1] + 3 * model.x[2])
model.Constraint1 = pyo.Constraint(expr=3 * model.x[1] + 4 * model.x[2] >= 1)
solver = pyo.SolverFactory("cplex")
results = solver.solve(model, tee=True)
```

### Error Message

```
Welcome to IBM(R) ILOG(R) CPLEX(R) Interactive Optimizer 22.1.0.0
  with Simplex, Mixed Integer & Barrier Optimizers
5725-A06 5725-A29 5724-Y48 5724-Y49 5724-Y54 5724-Y55 5655-Y21
Copyright IBM Corp. 1988, 2022.  All Rights Reserved.

Type 'help' for a list of available commands.
Type 'help' followed by a command name for more
information on commands.

CPLEX> Logfile 'cplex.log' closed.
Logfile '/var/folders/87/h47k8xb11z973ssypvcqgmq80000gn/T/tmpxm3u9qwg.cplex.log' open.
CPLEX> Problem '/var/folders/87/h47k8xb11z973ssypvcqgmq80000gn/T/tmpm0zpegx3.pyomo.lp' read.
Read time = 0.01 sec. (0.00 ticks)
CPLEX> Problem name         : /var/folders/87/h47k8xb11z973ssypvcqgmq80000gn/T/tmpm0zpegx3.pyomo.lp
Objective sense      : Minimize
Variables            :       3
Objective nonzeros   :       2
Linear constraints   :       2  [Greater: 1,  Equal: 1]
  Nonzeros           :       3
  RHS nonzeros       :       2

Variables            : Min LB: 0.000000         Max UB: all infinite   
Objective nonzeros   : Min   : 2.000000         Max   : 3.000000       
Linear constraints   :
  Nonzeros           : Min   : 1.000000         Max   : 4.000000       
  RHS nonzeros       : Min   : 1.000000         Max   : 1.000000       
CPLEX> Version identifier: 22.1.0.0 | 2022-03-09 | 1a383f8ce
Tried aggregator 1 time.
LP Presolve eliminated 2 rows and 3 columns.
All rows and columns eliminated.
Presolve time = 0.00 sec. (0.00 ticks)

Dual simplex - Optimal:  Objective =  6.6666666667e-01
Solution time =    0.01 sec.  Iterations = 0 (0)
Deterministic time = 0.00 ticks  (0.13 ticks/sec)

CPLEX> Solution written to file '/var/folders/87/h47k8xb11z973ssypvcqgmq80000gn/T/tmp2td6qj9h.cplex.sol'.
CPLEX> Traceback (most recent call last):
  File "/Users/ernesto/python_projects/cplex_test/main.py", line 27, in <module>
    run_model()
  File "/Users/ernesto/python_projects/cplex_test/main.py", line 21, in run_model
    results = solver.solve(model, tee=True)
  File "/Users/ernesto/python_projects/pump-facility-optimizer/__pypackages__/3.9/lib/pyomo/opt/base/solvers.py", line 605, in solve
    result = self._postsolve()
  File "/Users/ernesto/python_projects/pump-facility-optimizer/__pypackages__/3.9/lib/pyomo/solvers/plugins/solvers/CPLEX.py", line 885, in _postsolve
    results = ILMLicensedSystemCallSolver._postsolve(self)
  File "/Users/ernesto/python_projects/pump-facility-optimizer/__pypackages__/3.9/lib/pyomo/opt/solver/shellcmd.py", line 270, in _postsolve
    results = self.process_output(self._rc)
  File "/Users/ernesto/python_projects/pump-facility-optimizer/__pypackages__/3.9/lib/pyomo/opt/solver/shellcmd.py", line 332, in process_output
    self.process_soln_file(results)
  File "/Users/ernesto/python_projects/pump-facility-optimizer/__pypackages__/3.9/lib/pyomo/solvers/plugins/solvers/CPLEX.py", line 771, in process_soln_file
    objective_value = (tokens[0].split('=')[1].strip()).lstrip("\"").rstrip("\"")
IndexError: list index out of range

```

### Information on your system

Pyomo version: 6.4.0
Python version: 3.9.7
Operating system: macOS 11.6
Pyomo was installed using PyPI
Solver: CPLEX 22.1.0.0

### Additional information

Here is the .sol file:

```
<?xml version = "1.0" encoding="UTF-8" standalone="yes"?>
<CPLEXSolution version="1.2">
 <header
   problemName="/var/folders/87/h47k8xb11z973ssypvcqgmq80000gn/T/tmpm0zpegx3.pyomo.lp"
   objectiveValue="0.66666666666666663"
   solutionTypeValue="1"
   solutionTypeString="basic"
   solutionStatusValue="1"
   solutionStatusString="optimal"
   solutionMethodString="dual"
   primalFeasible="1"
   dualFeasible="1"
   simplexIterations="0"
   writeLevel="1"/>
 <quality
   epRHS="9.9999999999999995e-07"
   epOpt="9.9999999999999995e-07"
   maxPrimalInfeas="0"
   maxDualInfeas="0"
   maxPrimalResidual="5.5511151231257827e-17"
   maxDualResidual="0"
   maxX="1"
   maxPi="0.66666666666666663"
   maxSlack="0"
   maxRedCost="0.33333333333333348"
   kappa="3"/>
 <linearConstraints>
  <constraint name="c_l_x4_" index="0" status="LL" slack="0" dual="0.66666666666666663"/>
  <constraint name="c_e_ONE_VAR_CONSTANT" index="1" status="LL" slack="0" dual="0"/>
 </linearConstraints>
 <variables>
  <variable name="x1" index="0" status="BS" value="0.33333333333333331" reducedCost="0"/>
  <variable name="x2" index="1" status="LL" value="0" reducedCost="0.33333333333333348"/>
  <variable name="ONE_VAR_CONSTANT" index="2" status="BS" value="1" reducedCost="0"/>
 </variables>
 <objectiveValues>
  <objective index="0" name="x3" value="0.66666666666666663"/>
 </objectiveValues>
</CPLEXSolution>
```

**Comment by ernestoar** [comment]
Apologies, this was caused by a glitch on my setup causing an older version of Pyomo to be used, nothing to fix.
