### ISSUE TITLE
Gurobi direct does not work with DerivativeVars

### ISSUE THREAD

**Issue by kenasa92** [Pyomo/pyomo#2439]
## Summary

When working with `DerivativeVar` from pyomo.dae and the gurobi solver, the option `SolverFactory('gurobi', solver_io='direct')` raises an error. This also happens when using the `persistent` option. However, the problem solves well for `solver_io ='lp'`

### Steps to reproduce the issue

This short code snippet should reproduce the error: 

```console
from pyomo.environ import ConcreteModel, Constraint, Var, Set, Objective, SolverFactory, Binary
from pyomo.dae import DerivativeVar, ContinuousSet


cost = [100, 50, 400, 200, 50]
model = ConcreteModel(name='model')
model.time_set = ContinuousSet(initialize=[0, 1, 2, 3, 4])
model.x = Var(model.time_set, domain=Binary, initialize=1)
model.x_dt = DerivativeVar(model.x, wrt=model.time_set)

# Constraints
def cons1_rule(model, ti):
    return model.x_dt[ti] >= 0

model.cons1 = Constraint(model.time_set, rule=cons1_rule)

def cons2_rule(model):
    return sum(model.x[i] for i in model.time_set) >= 2

model.cons2 = Constraint(rule=cons2_rule)


def obj_rule(model):
    return sum(model.x[ti]*ci for ti, ci in zip(model.time_set, cost))

model.obj = Objective(rule=obj_rule)


opt = SolverFactory('gurobi', solver_io='direct')
opt.solve(model, tee=True)

```

### Error Message

```console
Traceback (most recent call last):
  File "C:\Users\testenviroment\lib\site-packages\pyomo\common\collections\component_map.py", line 94, in __getitem__
    return self._dict[id(obj)][1]
KeyError: 2419757942488

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/test_reproduce_error_derivative_gurobi.py", line 42, in <module>
    opt.solve(model, tee=True)
  File "C:\Users\testenviroment\lib\site-packages\pyomo\solvers\plugins\solvers\direct_solver.py", line 119, in solve
    self._presolve(*args, **kwds)
  File "C:\Users\testenviroment\lib\site-packages\pyomo\solvers\plugins\solvers\direct_solver.py", line 62, in _presolve
    self._set_instance(model, kwds)
  File "C:\Users\testenviroment\lib\site-packages\pyomo\solvers\plugins\solvers\gurobi_direct.py", line 297, in _set_instance
    self._add_block(model)
  File "C:\Users\testenviroment\lib\site-packages\pyomo\solvers\plugins\solvers\gurobi_direct.py", line 314, in _add_block
    DirectOrPersistentSolver._add_block(self, block)
  File "C:\Users\testenviroment\lib\site-packages\pyomo\solvers\plugins\solvers\direct_or_persistent_solver.py", line 217, in _add_block
    self._add_constraint(con)
  File "C:\Users\testenviroment\lib\site-packages\pyomo\solvers\plugins\solvers\gurobi_direct.py", line 337, in _add_constraint
    self._max_constraint_degree)
  File "C:\Users\testenviroment\lib\site-packages\pyomo\solvers\plugins\solvers\gurobi_direct.py", line 242, in _get_expr_from_pyomo_expr
    gurobi_expr, referenced_vars = self._get_expr_from_pyomo_repn(repn, max_degree)
  File "C:\Users\testenviroment\lib\site-packages\pyomo\solvers\plugins\solvers\gurobi_direct.py", line 221, in _get_expr_from_pyomo_repn
    new_expr = gurobipy.LinExpr(repn.linear_coefs, [self._pyomo_var_to_solver_var_map[i] for i in repn.linear_vars])
  File "C:\Users\testenviroment\lib\site-packages\pyomo\solvers\plugins\solvers\gurobi_direct.py", line 221, in <listcomp>
    new_expr = gurobipy.LinExpr(repn.linear_coefs, [self._pyomo_var_to_solver_var_map[i] for i in repn.linear_vars])
  File "C:\Users\testenviroment\lib\site-packages\pyomo\common\collections\component_map.py", line 97, in __getitem__
    % (id(obj), str(obj)))
KeyError: "Component with id '2419757942488': x_dt[0]"

Process finished with exit code 1

```

### Information on your system

Pyomo version: 6.4.0 
Python version: 3.7.7
Operating system: Windows
How Pyomo was installed (PyPI, conda, source): pip
Solver (if applicable): gurobi

### Additional information

I think this error is because direct gurobi solvers try to link `DerivativeVar` to an equivalent in gurobipy. However, this is not currently possible since in Gurobi discretizations must be made "by hand". 

I think that one possible way of solving this could be avoiding linking gurobipy and pyomo for `DerivativeVar`, since (as I understand) they are translated into constraints for the model.

**Comment by kenasa92** [comment]
Thank you @michaelbynum, you are right. This problem is missing a transformation and that's why the solver did not work. Now it works just fine both for this example and my problem.
Silly mistake of mine. The problem I am working on calls the solver through another method which also defines the transformation. So, when I tested other solvers by just calling the pyomo method I missed the transformation. 

Sorry for the inconvenience and thank you very much!

**Comment by michaelbynum** [comment]
No worries at all. I'm just glad it works!
