### ISSUE TITLE
Setting CONFIG attributes for gdpopt results in ValueError: Key '...' not defined in ConfigDict '' and Dict disallows implicit entries

### ISSUE THREAD

**Issue by lbianchi-lbl** [Pyomo/pyomo#2500]
## Summary

After updating (indirectly, through IDAES) Pyomo to 6.4.2 in gmlc-dispatches/dispatches#136, this code snippet results in an error:

```py
opt = SolverFactory('gdpopt')
opt.CONFIG.strategy = 'RIC'
opt.CONFIG.tee = False
opt.CONFIG.mip_solver = 'cbc'
opt.CONFIG.nlp_solver = 'ipopt'
opt.CONFIG.init_strategy = "no_init"
```

```txt
self = <pyomo.common.config.ConfigDict object at 0x7fda20ef81b0>
name = 'strategy', config = 'RIC'

    def add(self, name, config):
        if not self._implicit_declaration:
            raise ValueError("Key '%s' not defined in ConfigDict '%s'"
                             " and Dict disallows implicit entries" %
>                            (name, self.name(True)))
E           ValueError: Key 'strategy' not defined in ConfigDict '' and Dict disallows implicit entries

/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pyomo/common/config.py:2262: ValueError
```

I've managed to strip down the issue to `from pyomo.environ import SolverFactory as F; F('gdpopt').CONFIG.strategy = 'RIC'`, and using that for `git bisect` between 6.4.1 and 6.4.2 of Pyomo/pyomo:main, I got the following:

```console
$ git bisect run pip uninstall --yes pyomo ; pip install . ; python -c "from pyomo.environ import SolverFactory as F; F('gdpopt').CONFIG.strategy = 'RIC'"
running pip uninstall --yes pyomo
Found existing installation: Pyomo 6.4.2
Uninstalling Pyomo-6.4.2:
  Successfully uninstalled Pyomo-6.4.2
Bisecting: 169 revisions left to test after this (roughly 7 steps)
[0bff05db3722be5836f276b4ed7e1b49002faae8] Fix logic when tracing through nested named expressions
running pip uninstall --yes pyomo
WARNING: Skipping pyomo as it is not installed.
Bisecting: 84 revisions left to test after this (roughly 6 steps)
[5481d2bf76ff76946d538ac018fc88b6fe2dc529] Merge branch 'Pyomo:main' into fix_error_handling_in_quicksum
running pip uninstall --yes pyomo
WARNING: Skipping pyomo as it is not installed.
Bisecting: 42 revisions left to test after this (roughly 5 steps)
[afe8b61b99f9773b9af3377b1fb88fcc20c99f48] Adding placeholder for using appsi fbbt eventually.
running pip uninstall --yes pyomo
WARNING: Skipping pyomo as it is not installed.
Bisecting: 23 revisions left to test after this (roughly 5 steps)
[59eb1043ed45e079833a97f77c2461b83a2d010d] NFC: additional documentation
running pip uninstall --yes pyomo
WARNING: Skipping pyomo as it is not installed.
Bisecting: 10 revisions left to test after this (roughly 4 steps)
[e73b024ff562ae9120da415fd1e5bdd64fd8cea6] Merge pull request #2490 from jsiirola/timer-tests-win10
running pip uninstall --yes pyomo
WARNING: Skipping pyomo as it is not installed.
Bisecting: 5 revisions left to test after this (roughly 3 steps)
[9f043902df7315a4fc65e128fa1aacd5fbfb7afe] Make test platform agnostic
running pip uninstall --yes pyomo
WARNING: Skipping pyomo as it is not installed.
Bisecting: 2 revisions left to test after this (roughly 2 steps)
[c568fbe290553513e8d43147c905f04f16623d18] Merge pull request #2492 from jsiirola/relocate-module
running pip uninstall --yes pyomo
WARNING: Skipping pyomo as it is not installed.
Bisecting: 0 revisions left to test after this (roughly 1 step)
[b61a4ac522920f09f94e352215f1b45432ee0ab1] Finalizing the 6.4.2 release (readme, deprecations, changelog, version number)
running pip uninstall --yes pyomo
WARNING: Skipping pyomo as it is not installed.
3333cecec999c7c0f205a4b015f84dc0178668cb is the first bad commit
commit 3333cecec999c7c0f205a4b015f84dc0178668cb
Merge: c568fbe29 b61a4ac52
Author: Bethany Nicholson <blnicho@users.noreply.github.com>
Date:   Wed Aug 17 11:55:55 2022 -0400

    Merge pull request #2495 from blnicho/finalize-release-6.4.2
    
    Finalize release 6.4.2

 .coin-or/projDesc.xml                          |  4 +-
 CHANGELOG.txt                                  | 73 +++++++++++++++++++++++---
 README.md                                      |  2 -
 RELEASE.txt                                    |  2 +-
 pyomo/common/timing.py                         |  4 +-
 pyomo/contrib/gdpopt/config_options.py         |  4 +-
 pyomo/contrib/gdpopt/solve_discrete_problem.py |  4 +-
 pyomo/contrib/gdpopt/util.py                   |  2 +-
 pyomo/contrib/parmest/ipopt_solver_wrapper.py  | 10 ++--
 pyomo/version/info.py                          |  4 +-
 setup.py                                       |  1 +
 11 files changed, 82 insertions(+), 28 deletions(-)
bisect run success
Processing /tmp/pyomo
  Preparing metadata (setup.py) ... done
Requirement already satisfied: ply in /opt/conda/envs/test-pyomo-gdpopt/lib/python3.8/site-packages (from Pyomo==6.4.2) (3.11)
Building wheels for collected packages: Pyomo
  Building wheel for Pyomo (setup.py) ... done
  Created wheel for Pyomo: filename=Pyomo-6.4.2-py2.py3-none-any.whl size=2800261 sha256=98611e962a9b0a6da9f392ff7942640186f19b815bfe0775ec0cfcbcc5e642f4
  Stored in directory: /tmp/pip-ephem-wheel-cache-gy1nibm7/wheels/e3/c2/c1/234366e9ec833a6c71309fcdf10afa69d0545987d8c55fea96
Successfully built Pyomo
Installing collected packages: Pyomo
Successfully installed Pyomo-6.4.2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pyomo/pyomo/common/config.py", line 2179, in __setattr__
    ConfigDict.__setitem__(self, name, value)
  File "/tmp/pyomo/pyomo/common/config.py", line 2140, in __setitem__
    self.add(key, val)
  File "/tmp/pyomo/pyomo/common/config.py", line 2260, in add
    raise ValueError("Key '%s' not defined in ConfigDict '%s'"
ValueError: Key 'strategy' not defined in ConfigDict '' and Dict disallows implicit entries
```

Looking at 3333cece (which happens to have a very pleasant hash), I thought this deprecation could somehow be causing the issue: https://github.com/Pyomo/pyomo/commit/3333cecec999c7c0f205a4b015f84dc0178668cb#diff-904ca7208d20f2752cee5dc67fce46d0cd1f2b5b1cc90818f199f0159519d1fa

However, even after using the new `algorithm` key, the problem still persists:

```console
$ pip install pyomo==6.4.2 && python -c "from pyomo.environ import SolverFactory as F; F('gdpopt').CONFIG.algorithm = 'RIC'"
Collecting pyomo==6.4.2
  Using cached Pyomo-6.4.2-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (14.6 MB)
Requirement already satisfied: ply in /opt/conda/envs/test-pyomo-gdpopt/lib/python3.8/site-packages (from pyomo==6.4.2) (3.11)
Installing collected packages: pyomo
  Attempting uninstall: pyomo
    Found existing installation: Pyomo 6.4.1
    Uninstalling Pyomo-6.4.1:
      Successfully uninstalled Pyomo-6.4.1
Successfully installed pyomo-6.4.2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pyomo/pyomo/common/config.py", line 2179, in __setattr__
    ConfigDict.__setitem__(self, name, value)
  File "/tmp/pyomo/pyomo/common/config.py", line 2140, in __setitem__
    self.add(key, val)
  File "/tmp/pyomo/pyomo/common/config.py", line 2260, in add
    raise ValueError("Key '%s' not defined in ConfigDict '%s'"
ValueError: Key 'algorithm' not defined in ConfigDict '' and Dict disallows implicit entries
```

### Steps to reproduce the issue

```console
$ pip install pyomo==6.4.2 && python -c "from pyomo.environ import SolverFactory as F; F('gdpopt').CONFIG.algorithm = 'RIC'"
```

### Error Message

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pyomo/pyomo/common/config.py", line 2179, in __setattr__
    ConfigDict.__setitem__(self, name, value)
  File "/tmp/pyomo/pyomo/common/config.py", line 2140, in __setitem__
    self.add(key, val)
  File "/tmp/pyomo/pyomo/common/config.py", line 2260, in add
    raise ValueError("Key '%s' not defined in ConfigDict '%s'"
ValueError: Key 'algorithm' not defined in ConfigDict '' and Dict disallows implicit entries
```

### Information on your system

Solver: `gdpopt`

```sh
$ bash -c 'for cmd in "pyomo --version" "python --version" "uname -a" "which python" ; do echo "$cmd:" $($cmd) ; done'
pyomo --version: Pyomo 6.4.2 (CPython 3.8.13 on Linux 5.4.0-122-generic)
python --version: Python 3.8.13
uname -a: Linux eks 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
which python: /opt/conda/envs/test-pyomo-gdpopt/bin/python
```

**Comment by jsiirola** [comment]
This is a known change.  In the GDPopt refactor, "GDPopt" was broken apart into separate classes to simplify the code and make reuse and extension easier.  Unfortunately, there wasn't a way to preserve this specific use case.  @emma58 warned @esrawli this would be changing.

The "quick" fix is:
```diff
- opt = SolverFactory('gdpopt')
- opt.CONFIG.strategy = 'RIC'
+ opt = SolverFactory('gdpopt.ric')
```

**Comment by lbianchi-lbl** [comment]
@emma58 @jsiirola thanks for the clarification. The suggested change (using `gdpopt.ric`) resolves the specific exception mentioned in this issue, so I think this can be closed. I'm not sure what's the policy and/or convention for changes in contributed code, but maybe it might be worth adding a mention of this to the [6.4.2 release notes](https://github.com/Pyomo/pyomo/releases/tag/6.4.2)?
