### ISSUE TITLE
CBC plugin not detecting Stopped by Time Limit correctly

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#256]
This issue is based on a StackOverflow question: https://stackoverflow.com/questions/47334254/error-reported-while-running-pyomo-optimization-with-cbc-solver-and-using-timeli/

Op reports error message
```
Traceback (most recent call last):
  File "model_final.py", line 392, in 
    solver.solve(model, timelimit = 60*1, tee=True)
  File "/home/aditya/0r/lib/python2.7/site-packages/pyomo/opt/base/solvers.py", line 655, in solve
    default_variable_value=self._default_variable_value)
  File "/home/aditya/0r/lib/python2.7/site-packages/pyomo/core/base/PyomoModel.py", line 242, in load_from
    % str(results.solver.status))
ValueError: Cannot load a SolverResults object with bad status: error
```
First few lines of solution file:
```
Stopped on time - objective value -1411.99922848
      0 c_e_x1454_                         0                       0
      1 c_e_x1455_                         0                       0
      2 c_e_x1456_                         0                       0
      3 c_e_x1457_                         0                       0
      4 c_e_x1458_                         0                       0
      5 c_e_x1459_                         0                       0
      6 c_e_x1460_                         0                       0
      7 c_e_x1461_                         0                       0
      8 c_e_x1462_                         0                       0
```

**Comment by manish-byteprophecy** [comment]
I have created a pull request (https://github.com/Pyomo/pyomo/pull/265) to address this issue. If somebody with the right access can merge the same that would be great.

**Comment by blnicho** [comment]
The PR addressing this issue was merged. Closing this.
