### ISSUE TITLE
Could not write legal LP file

### ISSUE THREAD

**Issue by Betristor** [Pyomo/pyomo#2562]
## Summary
Pyomo could not solve the linear model and report bug as follows:
```
  File "pyomo/repn/plugins/cpxlp.pyx", line 158, in pyomo.repn.plugins.cpxlp.ProblemWriter_cpxlp.__call__
  File "pyomo/repn/plugins/cpxlp.pyx", line 159, in pyomo.repn.plugins.cpxlp.ProblemWriter_cpxlp.__call__
  File "pyomo/repn/plugins/cpxlp.pyx", line 160, in pyomo.repn.plugins.cpxlp.ProblemWriter_cpxlp.__call__
  File "pyomo/repn/plugins/cpxlp.pyx", line 532, in pyomo.repn.plugins.cpxlp.ProblemWriter_cpxlp._print_model_LP
RuntimeError: Cannot write legal LP file.  Objective 'objective' has nonlinear terms that are not quadratic.
```

Main problem may be related to cpxlp.pyx file.

### Error Message

```console
Traceback (most recent call last):
  File "/Users/xxx/Documents/GitHub/Adaptive-clustering-for-ESOM/src/main.py", line 90, in <module>
    m = solve(m, config)
  File "/Users/xxx/Documents/GitHub/Adaptive-clustering-for-ESOM/src/solve_model.py", line 13, in solve
    opt.solve(m)
  File "/Users/xxx/miniforge3/envs/eso/lib/python3.8/site-packages/pyomo/opt/base/solvers.py", line 570, in solve
    self._presolve(*args, **kwds)
  File "/Users/xxx/miniforge3/envs/eso/lib/python3.8/site-packages/pyomo/solvers/plugins/solvers/GUROBI.py", line 234, in _presolve
    ILMLicensedSystemCallSolver._presolve(self, *args, **kwds)
  File "/Users/xxx/miniforge3/envs/eso/lib/python3.8/site-packages/pyomo/opt/solver/shellcmd.py", line 209, in _presolve
    OptSolver._presolve(self, *args, **kwds)
  File "/Users/xxx/miniforge3/envs/eso/lib/python3.8/site-packages/pyomo/opt/base/solvers.py", line 667, in _presolve
    self._convert_problem(args,
  File "/Users/xxx/miniforge3/envs/eso/lib/python3.8/site-packages/pyomo/opt/base/solvers.py", line 718, in _convert_problem
    return convert_problem(args,
  File "/Users/xxx/miniforge3/envs/eso/lib/python3.8/site-packages/pyomo/opt/base/convert.py", line 101, in convert_problem
    problem_files, symbol_map = converter.apply(*tmp, **tmpkw)
  File "/Users/xxx/miniforge3/envs/eso/lib/python3.8/site-packages/pyomo/solvers/plugins/converter/model.py", line 78, in apply
    instance.write(
  File "/Users/xxx/miniforge3/envs/eso/lib/python3.8/site-packages/pyomo/core/base/block.py", line 1976, in write
    (filename, smap) = problem_writer(self,
  File "pyomo/repn/plugins/cpxlp.pyx", line 158, in pyomo.repn.plugins.cpxlp.ProblemWriter_cpxlp.__call__
  File "pyomo/repn/plugins/cpxlp.pyx", line 159, in pyomo.repn.plugins.cpxlp.ProblemWriter_cpxlp.__call__
  File "pyomo/repn/plugins/cpxlp.pyx", line 160, in pyomo.repn.plugins.cpxlp.ProblemWriter_cpxlp.__call__
  File "pyomo/repn/plugins/cpxlp.pyx", line 532, in pyomo.repn.plugins.cpxlp.ProblemWriter_cpxlp._print_model_LP
RuntimeError: Cannot write legal LP file.  Objective 'objective' has nonlinear terms that are not quadratic.
```

### Information on your system

Pyomo version: 6.4.2
Python version: 3.8.13
Operating system: MacOS Monterey, M1 Pro
How Pyomo was installed (PyPI, conda, source): conda
Solver (if applicable): gurobi, cbc, clp, highs, ipopt, glpk are all tested. Gurobi, cbc, glpk reports the same error and clp didn't find the temporary model file. So maybe the underlying logic is the same. 

### Additional information
Same problem on stackoverflow.
https://stackoverflow.com/questions/61217721/runtimeerror-cannot-write-legal-lp-file-objective-maximum-profit-has-nonline/74016061#74016061
And like my post on this problem, neither my code did have some nonlinear terms nor pyomo has somthing wrong.
I will have another guy check my code as well, but at the same time, I report the problem for insurance.

**Comment by Betristor** [comment]
Sure, thanks for your suggestions.
```
# Costs calculation
# Objective calculation
def obj_value(m):
    return m.total_cost == m.cost_inv + m.cost_var + m.cost_nse

m.objective = Objective(rule=obj_value, sense=minimize)

# Investment calculation
def cost_inv_cal(m):
    return m.cost_inv == m.cost_inv_the + m.cost_inv_vre + m.cost_inv_sto
m.expr_cost_inv = Constraint(rule=cost_inv_cal)

# Thermal investment cost
def cost_inv_the_cal(m):
    return m.cost_inv_the == sum(m.thermal_capacity[k] * c_inv_the[k] for k in m.K)
m.expr_cost_inv_the = Constraint(rule=cost_inv_the_cal)

# Renewable investment cost
def cost_inv_vre_cal(m):
    return m.cost_inv_vre == sum(m.renewable_capacity[r] * c_inv_vre[r] for r in m.R)
m.expr_cost_inv_vre = Constraint(rule=cost_inv_vre_cal)

# Storage investment cost
def cost_inv_sto_cal(m):
    return m.cost_inv_sto == sum(m.storage_energy_capacity[s] * c_inv_sto_energy[s] + m.storage_power_capacity[s] * c_inv_sto_power[s] for s in m.S)
m.expr_inv_sto = Constraint(rule=cost_inv_sto_cal)

# Operation calculation
def cost_var_cal(m):
    return m.cost_var == m.cost_var_the + m.cost_var_the_start + m.cost_var_sto
m.expr_cost_var = Constraint(rule=cost_var_cal)

# Thermal operation variable costs
def cost_var_the_cal(m):
    return m.cost_var_the == sum(sum(m.weights[t] * m.thermal_power[k, t] * c_var_the[k] for k in m.K) for t in m.T)
m.expr_cost_var_the = Constraint(rule=cost_var_the_cal)

# Thermal startup operation costs
def cost_var_the_start_cal(m):
    return m.cost_var_the_start == sum(sum(m.weights[t] * m.thermal_start[k, t] * c_var_the_start[k] for k in m.K) for t in m.T)
m.expr_cost_var_the_start = Constraint(rule=cost_var_the_start_cal)

# Storage operation costs
def cost_var_sto_cal(m):
    return m.cost_var_sto == sum(sum(m.weights[t] * (m.storage_discharge[s, t] + m.storage_charge[s, t]) * c_var_sto[s] for s in m.S) for t in m.T)
m.expr_cost_var_sto = Constraint(rule=cost_var_sto_cal)

# Non served energy costs
def cost_nse_cal(m):
    return m.cost_nse == sum(m.weights[t] * m.non_served_energy[t] * c_nse for t in m.T)
m.expr_cost_nse = Constraint(rule=cost_nse_cal)
```

**Comment by jsiirola** [comment]
Your objective is indeed not a linear or quadratic expression: it is an equality expression (which evaluates to a Boolean and not a floating point number).  Switching the objective to
```python
def obj_value(m):
    return m.cost_inv + m.cost_var + m.cost_nse
```
will resolve the error.

The problem here is not with the LP writer, but rather with the error checking in the Objective constructor (it should complain about an invalid non-numeric expression).

**Comment by Betristor** [comment]
＼（＾ ＾）／,much thanks, it solved my problem perfectly!!!
