### ISSUE TITLE
Use cyipopt with Mindtpy

### ISSUE THREAD

**Issue by jialuw96** [Pyomo/pyomo#2767]
## Summary

When using the GreyBox model in Pyomo, we get an error message saying cyipopt cannot be used with mindtpy. 

### Description

Error message: 
Traceback (most recent call last):
  File "/home/parallels/anaconda3/envs/pyomo/lib/python3.7/site-packages/pyomo/common/config.py", line 1262, in _cast
    return self._domain(value)
  File "/home/parallels/anaconda3/envs/pyomo/lib/python3.7/site-packages/pyomo/common/config.py", line 249, in __call__
    raise ValueError("value %s not in domain %s" % (value, self._domain))
ValueError: value cyipopt not in domain ['ipopt', 'gams', 'baron']

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "rotary-bed-cost-strategy.py", line 439, in <module>
    results = solver.solve(mod, mip_solver='gurobi_persistent', nlp_solver='cyipopt', tee=True, integer_tolerance=0.5)
  File "/home/parallels/anaconda3/envs/pyomo/lib/python3.7/site-packages/pyomo/contrib/mindtpy/MindtPy.py", line 79, in solve
    config.set_value(kwds)
  File "/home/parallels/anaconda3/envs/pyomo/lib/python3.7/site-packages/pyomo/common/config.py", line 2193, in set_value
    self[key] = value[_decl_map[key]]
  File "/home/parallels/anaconda3/envs/pyomo/lib/python3.7/site-packages/pyomo/common/config.py", line 2010, in __setitem__
    self._data[_key].set_value(val)
  File "/home/parallels/anaconda3/envs/pyomo/lib/python3.7/site-packages/pyomo/common/config.py", line 1652, in set_value
    self._data = self._cast(value)
  File "/home/parallels/anaconda3/envs/pyomo/lib/python3.7/site-packages/pyomo/common/config.py", line 1273, in _cast
    (self.name(True), value, _dom, err))
ValueError: invalid value for configuration 'nlp_solver':
	Failed casting cyipopt
	to <class 'pyomo.common.config.In'>
	Error: value cyipopt not in domain ['ipopt', 'gams', 'baron']
```

**Comment by jialuw96** [comment]
The example is in: https://github.com/jialuw96/pyomo/tree/cyipopt_debug/pyomo/contrib/mindtpy/greybox_test_example

This folder includes two .py files, cyipopt_example.py contains the grey-box problem, greybox_generalize.py contains greybox module generalizations. 

Below are the results for three cases on my machine. My software version: 
- IDAES: 2.1.0
- Pynumero-libraries: 1.3
- pyomo: 6.6.2.dev0

Case 1: Discrete variables left as Degrees of Freedom 

`PyNumero does not support discrete variables `

Case 2: Discrete variables fixed 

```
This is Ipopt version 3.13.3, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:       31
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        0

Total number of variables............................:       16
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:       16
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0


 Consider M =
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0]
   logdet =  0.0 

Eigvals: [1. 1. 1. 1. 1.]
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0 -0.0000000e+00 0.00e+00 1.00e+00   0.0 0.00e+00    -  0.00e+00 0.00e+00   0

Number of Iterations....: 0

                                   (scaled)                 (unscaled)
Objective...............:  -0.0000000000000000e+00   -0.0000000000000000e+00
Dual infeasibility......:   0.0000000000000000e+00    0.0000000000000000e+00
Constraint violation....:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   0.0000000000000000e+00    0.0000000000000000e+00
Overall NLP error.......:   0.0000000000000000e+00    0.0000000000000000e+00


Number of objective function evaluations             = 1
Number of objective gradient evaluations             = 1
Number of equality constraint evaluations            = 1
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 1
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 0
Total CPU secs in IPOPT (w/o function evaluations)   =      0.007
Total CPU secs in NLP function evaluations           =      0.007

EXIT: Optimal Solution Found.
```

Case 3: relax discrete decisions to continuous ones, left as DOFs 

```
******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************

This is Ipopt version 3.13.3, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:       46
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        0

Total number of variables............................:       31
                     variables with only lower bounds:        0
                variables with lower and upper bounds:       15
                     variables with only upper bounds:        0
Total number of equality constraints.................:       16
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0


 Consider M =
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0]
   logdet =  0.0 

Eigvals: [1. 1. 1. 1. 1.]
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0 -0.0000000e+00 0.00e+00 7.14e-01   0.0 0.00e+00    -  0.00e+00 0.00e+00   0

 Consider M =
 [[1.1348314 0.        0.        0.        0.       ]
 [0.        1.1348314 0.        0.        0.       ]
 [0.        0.        1.1348314 0.        0.       ]
 [0.        0.        0.        1.1348314 0.       ]
 [0.        0.        0.        0.        1.1348314]]
[1.134831404576443, 0.0, 0.0, 0.0, 0.0, 1.134831404576443, 0.0, 0.0, 0.0, 1.134831404576443, 0.0, 0.0, 1.134831404576443, 0.0, 1.134831404576443]
   logdet =  0.632420488382395 

Eigvals: [1.1348314 1.1348314 1.1348314 1.1348314 1.1348314]
   1 -6.7415702e-01 4.17e-02 6.74e-01  -5.3 6.74e-01    -  9.68e-01 1.00e+00f  1

 Consider M =
 [[4.00283181 0.         0.         0.         0.        ]
 [0.         4.00283181 0.         0.         0.        ]
 [0.         0.         4.00283181 0.         0.        ]
 [0.         0.         0.         4.00283181 0.        ]
 [0.         0.         0.         0.         4.00283181]]
[4.002831809272432, 0.0, 0.0, 0.0, 0.0, 4.002831809272432, 0.0, 0.0, 0.0, 4.002831809272432, 0.0, 0.0, 4.002831809272432, 0.0, 4.002831809272432]
   logdet =  6.935010314789839 

Eigvals: [4.00283181 4.00283181 4.00283181 4.00283181 4.00283181]
   2 -1.3268661e+01 6.33e+00 1.89e-01  -1.5 1.26e+01    -  1.00e+00 1.00e+00f  1

 Consider M =
 [[4.68582848 0.         0.         0.         0.        ]
 [0.         4.68582848 0.         0.         0.        ]
 [0.         0.         4.68582848 0.         0.        ]
 [0.         0.         0.         4.68582848 0.        ]
 [0.         0.         0.         0.         4.68582848]]
[4.685828479011311, 0.0, 0.0, 0.0, 0.0, 4.685828479011311, 0.0, 0.0, 0.0, 4.685828479011311, 0.0, 0.0, 4.685828479011311, 0.0, 4.685828479011311]
   logdet =  7.7227136827926754 

Eigvals: [4.68582848 4.68582848 4.68582848 4.68582848 4.68582848]
   3 -7.7881522e+00 6.54e-02 1.49e-01  -3.6 5.48e+00    -  9.98e-01 1.00e+00h  1

 Consider M =
 [[4.99685833 0.         0.         0.         0.        ]
 [0.         4.99685833 0.         0.         0.        ]
 [0.         0.         4.99685833 0.         0.        ]
 [0.         0.         0.         4.99685833 0.        ]
 [0.         0.         0.         0.         4.99685833]]
[4.9968583342901125, 0.0, 0.0, 0.0, 0.0, 4.9968583342901125, 0.0, 0.0, 0.0, 4.9968583342901125, 0.0, 0.0, 4.9968583342901125, 0.0, 4.9968583342901125]
   logdet =  8.044046909040631 

Eigvals: [4.99685833 4.99685833 4.99685833 4.99685833 4.99685833]
   4 -8.1010992e+00 5.71e-02 1.15e-01  -3.0 1.08e+00    -  1.00e+00 2.89e-01f  1

 Consider M =
 [[4.99996863 0.         0.         0.         0.        ]
 [0.         4.99996863 0.         0.         0.        ]
 [0.         0.         4.99996863 0.         0.        ]
 [0.         0.         0.         4.99996863 0.        ]
 [0.         0.         0.         0.         4.99996863]]
[4.999968632842901, 0.0, 0.0, 0.0, 0.0, 4.999968632842901, 0.0, 0.0, 0.0, 4.999968632842901, 0.0, 0.0, 4.999968632842901, 0.0, 4.999968632842901]
   logdet =  8.047158194915013 

Eigvals: [4.99996863 4.99996863 4.99996863 4.99996863 4.99996863]
   5 -8.0472492e+00 9.10e-05 1.97e-04  -3.7 5.39e-02    -  1.00e+00 9.98e-01h  1

 Consider M =
 [[5.00000004 0.         0.         0.         0.        ]
 [0.         5.00000004 0.         0.         0.        ]
 [0.         0.         5.00000004 0.         0.        ]
 [0.         0.         0.         5.00000004 0.        ]
 [0.         0.         0.         0.         5.00000004]]
[5.000000043352086, 0.0, 0.0, 0.0, 0.0, 5.000000043352086, 0.0, 0.0, 0.0, 5.000000043352086, 0.0, 0.0, 5.000000043352086, 0.0, 5.000000043352086]
   logdet =  8.047189605522588 

Eigvals: [5.00000004 5.00000004 5.00000004 5.00000004 5.00000004]
   6 -8.0471896e+00 1.42e-08 1.12e-07  -9.8 5.96e-05    -  1.00e+00 1.00e+00h  1

 Consider M =
 [[5.00000005 0.         0.         0.         0.        ]
 [0.         5.00000005 0.         0.         0.        ]
 [0.         0.         5.00000005 0.         0.        ]
 [0.         0.         0.         5.00000005 0.        ]
 [0.         0.         0.         0.         5.00000005]]
[5.000000049950008, 0.0, 0.0, 0.0, 0.0, 5.000000049950008, 0.0, 0.0, 0.0, 5.000000049950008, 0.0, 0.0, 5.000000049950008, 0.0, 5.000000049950008]
   logdet =  8.047189612120508 

Eigvals: [5.00000005 5.00000005 5.00000005 5.00000005 5.00000005]
   7 -8.0471896e+00 0.00e+00 3.86e-13 -11.0 7.65e-09    -  1.00e+00 1.00e+00h  1

Number of Iterations....: 7

                                   (scaled)                 (unscaled)
Objective...............:  -8.0471896121205084e+00   -8.0471896121205084e+00
Dual infeasibility......:   3.8602454566216693e-13    3.8602454566216693e-13
Constraint violation....:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   9.9999999999969298e-12    9.9999999999969298e-12
Overall NLP error.......:   9.9999999999969298e-12    9.9999999999969298e-12


Number of objective function evaluations             = 8
Number of objective gradient evaluations             = 8
Number of equality constraint evaluations            = 8
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 8
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 0
Total CPU secs in IPOPT (w/o function evaluations)   =      0.032
Total CPU secs in NLP function evaluations           =      0.017

EXIT: Optimal Solution Found.
```
