### ISSUE TITLE
Windows: CPLEX direct, solver_io="direct" throws error when tee=True and keepfiles=False

### ISSUE THREAD

**Issue by JasperNL** [Pyomo/pyomo#285]
Below is an example in which the error occurs. The problem is that `tee=True` seems to reserve the file, which is why `pyutilib` cannot remove the temporary files. The code is followed by the console output.

Setting `keepfiles=False` will 'solve' this issue, but this is not very asthetic. `results = opt.solve(m, tee=True, keepfiles=False)`.

```python
from pyomo.environ import *
from pyomo.opt import SolverFactory

# define the model
n_steps = 100
m = ConcreteModel()
m.STEPS = Set(initialize=range(n_steps))
m.target = Param(m.STEPS, initialize=lambda m, s: 1.0)
m.Build = Var()
m.Operate = Var(m.STEPS)
m.Meet_Target = Constraint(m.STEPS, rule=lambda m, s: m.Operate[s] >= m.target[s])
m.Operate_Limit = Constraint(m.STEPS, rule=lambda m, s: m.Operate[s] <= m.Build)
m.MinCost = Objective(
    rule=lambda m: n_steps * m.Build + sum(1.0 * m.Operate[s] for s in m.STEPS), 
    sense=minimize
)

# solve the model
opt = SolverFactory("cplex", solver_io="direct")
results = opt.solve(m, tee=True, keepfiles=False)
m.solutions.load_from(results)
```

```
CPXPARAM_Read_DataCheck                          1
CPXPARAM_Read_APIEncoding                        "UTF-8"
CPXPARAM_MIP_Strategy_CallbackReducedLP          0
Tried aggregator 1 time.
LP Presolve eliminated 200 rows and 101 columns.
All rows and columns eliminated.
Presolve time = 0.00 sec. (0.05 ticks)
Traceback (most recent call last):
  File "C:\Anaconda3\envs\python35\lib\site-packages\pyutilib\component\config\tempfiles.py", line 171, in pop
    os.remove(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Jasper\\AppData\\Local\\Temp\\tmp770of057.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "error.py", line 20, in <module>
    results = opt.solve(m, tee=True, keepfiles=False)
  File "C:\Anaconda3\envs\python35\lib\site-packages\pyomo\solvers\plugins\solvers\direct_solver.py", line 149, in solve
    result = self._postsolve()
  File "C:\Anaconda3\envs\python35\lib\site-packages\pyomo\solvers\plugins\solvers\cplex_direct.py", line 639, in _postsolve
    pyutilib.services.TempfileManager.pop(remove=not self._keepfiles)
  File "C:\Anaconda3\envs\python35\lib\site-packages\pyutilib\component\config\tempfiles.py", line 179, in pop
    os.remove(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Jasper\\AppData\\Local\\Temp\\tmp770of057.log'
```
Thank you for your great work!

**Comment by michaelbynum** [comment]
This script works fine on my mac with both keepfiles=True and keepfiles=False. Unfortunately it will be some time before I can test this on a Windows machine. 

What version of cplex are you using?

Given your email about the reduced_costs bug, I assume you are using the master branch of pyomo (as opposed to a specific release)?

Michael

**Comment by JasperNL** [comment]
Hi Michael,

I'm using CPLEX 12.7.1.0 (academic release). It is correct that I'm working on the master branch.

Thanks,
Jasper

**Comment by rinman24** [comment]
I am having the same issue. Any updates on this?

**Comment by BlackNellore** [comment]
On the note, this happens not only in CPLEX direct, but also in CPLEX persistent. I am having the same issue on Windows.
