### ISSUE TITLE
Error Bonmin-solver fromNEOS-server

### ISSUE THREAD

**Issue by trufak** [Pyomo/pyomo#2934]
Hello!
I get an error when running bonmin solver from NEOS server.
A similar problem was in the [issue](https://github.com/pyomo/pyomo/issues/2867).
However, I noticed that I get this error only if there is an integer variable (**model.s_gen[g,h]**) in one of the constraints:
```
def constr_e_ges_sut (model):
    p_gec = [sum([model.p_gen[g,h]*model.s_gen[g,h] for g in G]) for h in H]
    return sum(p_gec) == model.e_ges_sut
M_stakan.const_e_ges_sut= pyo.Constraint(rule=constr_e_ges_sut)
```
Tell me is this a problem of the NEOS server or my script?
Please update the email address in the script.

### Steps to reproduce the issue:
```
import pyomo.environ as pyo
from pyomo.gdp import Disjunction
import numpy as np
import os

os.environ['NEOS_EMAIL'] = 'email@address'

# исходные данные
# потребление
p_potr = [110836,110169,110543,111490,113073,115773,120200,123508,126095,
               126164,125927,124981,124471,124900,124607,124512,123885,124048,
               124463,124833,123409,119947,115714,112672]
# ГЭС
n_gen = 12 # количество генераторов ГЭС
p_gen_max=500
p_gen_min=0
p_zz_max=300
p_zz_min=200
# заданная выработка ГЭС
e_ges_sut = 24000
# минимальная нагрузка ГЭС (Рмин)
p_ges_min = [680,680,680,680,680,680,680,680,680,680,680,680,680,680,680,680,680,680,680,680,680,680,680,680]
# максимальная нагрузка ГЭС (Рмакс)
p_ges_max = [1198,1198,1198,1198,1198,1198,1198,1198,1198,
             1198,1198,1198,1198,1198,1198,1198,1198,1198,
             1198,1198,1198,1198,1198,1198]
# ограничение скоростей
p_up_limit = 1500
p_down_limit = 1500
middle_p_tec = (sum(p_potr) - e_ges_sut)/24

# формирование объекта модели pyomo
M_stakan = pyo.ConcreteModel('gdp_neptun')

# индексы
H = list(range(24)) # часы
G = list(range(n_gen)) # генераторы

# параметры
M_stakan.p_potr = pyo.Param(H,initialize=p_potr)    # график потребления
M_stakan.middle_p_tec = pyo.Param(initialize=middle_p_tec)  # средняя мощность ТЭС
M_stakan.e_ges_sut = pyo.Param(initialize=e_ges_sut)    # суточная выработка ГЭС
M_stakan.p_ges_min = pyo.Param(H,initialize=p_ges_min) # минимальная нагрузка ГЭС (Рмин)
M_stakan.p_ges_max = pyo.Param(H,initialize=p_ges_max) # максимальная нагрузка ГЭС (Рмакс)

# переменные
# мощности генераторов
M_stakan.p_gen = pyo.Var(G,H,domain=pyo.Reals,bounds=(p_gen_min,p_gen_max))  
# состояния генераторов  
M_stakan.s_gen = pyo.Var(G,H, domain=pyo.Integers, bounds=(0, 1))    

# целевая функция
def objRule(model):
    p_tec = [model.p_potr[h] - sum([model.p_gen[g,h]*model.s_gen[g,h] for g in G]) for h in H]
    return sum([(p_tec[h] - model.middle_p_tec) ** 2 for h in H])
M_stakan.obj = pyo.Objective(rule=objRule)

# ограничения
# равенство заданной суточной выработке ГЭС
def constr_e_ges_sut (model):
    p_gec = [sum([model.p_gen[g,h]*model.s_gen[g,h] for g in G]) for h in H]
    return sum(p_gec) == model.e_ges_sut
M_stakan.const_e_ges_sut= pyo.Constraint(rule=constr_e_ges_sut)
# Рмин и Рмакс ГЭС
def constr_p_ges_min (model, h):
    return sum(model.p_gen[...,h]) >= model.p_ges_min[h]
M_stakan.constr_p_ges_min= pyo.Constraint(H,rule=constr_p_ges_min)
def constr_p_ges_max (model, h):
    return sum(model.p_gen[...,h]) <= model.p_ges_max[h]
M_stakan.constr_p_ges_max= pyo.Constraint(H,rule=constr_p_ges_max)

# настройка решателя
solver = pyo.SolverFactory('bonmin')
solver_manager = pyo.SolverManagerFactory('neos')  

# решение
res = solver_manager.solve(M_stakan, opt=solver)

# вывод результата
p_ges_opt = [sum([M_stakan.p_gen[g,h].value*M_stakan.s_gen[g,h].value for g in G]) for h in H]
print(p_ges_opt)
print(sum(p_ges_opt))
print(pyo.value(M_stakan.obj))
```

### Error message:
ERROR: Error parsing NEOS solution file  NEOS log: Job 13279258 dispatched
password: kwRlEeoa
    ---------- Begin Solver Output -----------
    Condor submit: 'neos.submit' Condor submit: 'watchdog.submit' Job
    submitted to NEOS HTCondor pool.
Traceback (most recent call last):
  File "c:\dev\.conda\Lib\site-packages\pyomo\opt\plugins\sol.py", line 41, in __call__
    return self._load(f, res, soln, suffixes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\.conda\Lib\site-packages\pyomo\opt\plugins\sol.py", line 83, in _load
    raise ValueError("no Options line found")
ValueError: no Options line found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\dev\.conda\Lib\site-packages\pyomo\neos\plugins\kestrel_plugin.py", line 219, in _perform_wait_any
    solver_results = opt.process_output(rc)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\.conda\Lib\site-packages\pyomo\opt\solver\shellcmd.py", line 396, in process_output
    results = self._results_reader(
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\dev\.conda\Lib\site-packages\pyomo\opt\plugins\sol.py", line 45, in __call__
    raise ValueError(
ValueError: Error reading 'C:\Users\789\AppData\Local\Temp\tmp3s100j8c.neos.sol': no Options line found.
SOL File Output:
ERROR: An error occured with your submission.

ERROR: ERROR: An error occured with your submission.

**Comment by blnicho** [comment]
Can you try replacing this line:

    res = solver_manager.solve(M_stakan, opt=solver)

with

    res = solver_manager.solve(M_stakan, opt='bonmin')

I'm pretty sure you need to pass a string solver name to the `opt` keyword rather than a solver object.

**Comment by trufak** [comment]
Replaced...I keep getting the same error

**Comment by trufak** [comment]
The error was in the script.
Changed the s_gen variable to Boolean Var, moved the connection with it to a logical constraint.
```
M_stakan.p_gen = pyo.Var(G,H,domain=pyo.Reals,bounds=(p_gen_min,p_gen_max))  
M_stakan.s_gen = pyo.BooleanVar(G,H)    

def objRule(model):
    p_tec = [model.p_potr[h] - sum([model.p_gen[g,h] for g in G]) for h in H]
    return sum([(p_tec[h] - model.middle_p_tec) ** 2 for h in H])
M_stakan.obj = pyo.Objective(rule=objRule)

def constr_e_ges_sut (model):
    return sum(model.p_gen[...]) == model.e_ges_sut
M_stakan.const_e_ges_sut= pyo.Constraint(rule=constr_e_ges_sut)

def constr_p_ges_min (model, h):
    return sum(model.p_gen[...,h]) >= model.p_ges_min[h]
M_stakan.constr_p_ges_min= pyo.Constraint(H,rule=constr_p_ges_min)

def constr_p_ges_max (model, h):
    return sum(model.p_gen[...,h]) <= model.p_ges_max[h]
M_stakan.constr_p_ges_max= pyo.Constraint(H,rule=constr_p_ges_max)

def s_gen_logical_rule (model,g,h):
    return model.p_gen[g,h] == 0 if not model.s_gen[g,h] else pyo.Constraint.Skip
M_stakan.s_gen_logical_rule= pyo.LogicalConstraint(G,H,rule=s_gen_logical_rule)

pyo.TransformationFactory('gdp.bigm').apply_to(M_stakan)
```
