### ISSUE TITLE
persistent_solver set_instance fails with variable in deactivated block

### ISSUE THREAD

**Issue by ZedongPeng** [Pyomo/pyomo#3000]
## Summary

Assume we define a variable inside a block and deactivate the block. If the variable appears in an constraint outside of the block, `persistent_solver` will fail when `set_instance()`. However, the direct solver will not fail.
### Steps to reproduce the issue

```
# example.py
from pyomo.environ import *

m = ConcreteModel()

"""Set declarations"""
I = m.I = RangeSet(1, 4, doc='continuous variables')
J = m.J = RangeSet(1, 3, doc='discrete variables')

# initial point information for discrete variables
initY = {1: 1, 2: 0, 3: 1}
# initial point information for continuous variables
initX = {1: 0, 2: 0, 3: 0, 4: 0}

"""Variable declarations"""
# DISCRETE VARIABLES
m.b = Block()
Y = m.b.Y = Var(J, domain=Binary, initialize=initY)
m.b.deactivate()
# CONTINUOUS VARIABLES
X = m.X = Var(I, domain=NonNegativeReals, initialize=initX, bounds=(0, 2))

"""Constraint definitions"""
m.const4 = Constraint(expr=X[2] - X[1] <= 0)
m.const5 = Constraint(expr=X[2] - 2 * Y[1] <= 0)
m.const6 = Constraint(expr=X[1] - X[2] - 2 * Y[2] <= 0)
m.const7 = Constraint(expr=Y[1] + Y[2] <= 1)

"""Cost (objective) function definition"""
m.objective = Objective(
    expr=+5 * Y[1] + 6 * Y[2] + 8 * Y[3] + X[4], sense=minimize
)

# opt = SolverFactory('cplex')
opt = SolverFactory('cplex_persistent')
opt.set_instance(m)
result = opt.solve(m,tee=True)
print(result)

```

### Error Message

```console
$ # Output message here, including entire stack trace, if available
Traceback (most recent call last):
  File "/Users/zedongpeng/Github/pyomo/pyomo/common/collections/component_map.py", line 71, in __getitem__
    return self._dict[id(obj)][1]
KeyError: 4565602528

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zedongpeng/Github/pyomo/pyomo/contrib/mindtpy/tests/test.py", line 47, in <module>
    opt.set_instance(m)
  File "/Users/zedongpeng/Github/pyomo/pyomo/solvers/plugins/solvers/persistent_solver.py", line 90, in set_instance
    return self._set_instance(model, kwds)
  File "/Users/zedongpeng/Github/pyomo/pyomo/solvers/plugins/solvers/cplex_direct.py", line 384, in _set_instance
    self._add_block(model)
  File "/Users/zedongpeng/Github/pyomo/pyomo/solvers/plugins/solvers/cplex_direct.py", line 418, in _add_block
    self._add_constraint(con, lin_con_data)
  File "/Users/zedongpeng/Github/pyomo/pyomo/solvers/plugins/solvers/cplex_direct.py", line 451, in _add_constraint
    cplex_expr, referenced_vars = self._get_expr_from_pyomo_expr(
  File "/Users/zedongpeng/Github/pyomo/pyomo/solvers/plugins/solvers/cplex_direct.py", line 326, in _get_expr_from_pyomo_expr
    cplex_expr, referenced_vars = self._get_expr_from_pyomo_repn(
  File "/Users/zedongpeng/Github/pyomo/pyomo/solvers/plugins/solvers/cplex_direct.py", line 309, in _get_expr_from_pyomo_repn
    variables=[self._pyomo_var_to_ndx_map[var] for var in repn.linear_vars],
  File "/Users/zedongpeng/Github/pyomo/pyomo/solvers/plugins/solvers/cplex_direct.py", line 309, in <listcomp>
    variables=[self._pyomo_var_to_ndx_map[var] for var in repn.linear_vars],
  File "/Users/zedongpeng/Github/pyomo/pyomo/common/collections/component_map.py", line 73, in __getitem__
    raise KeyError("Component with id '%s': %s" % (id(obj), str(obj)))
KeyError: "Component with id '4565602528': b.Y[1]"
```

**Comment by michaelbynum** [comment]
I think this should be resolved in `contrib.solver`. The new interfaces do not care where variables live.
