### ISSUE TITLE
APPSI FBBT with nested `Expression` objects

### ISSUE THREAD

**Issue by bknueven** [Pyomo/pyomo#3184]
## Summary

APPSI FBBT sometimes raises an Exception with nested named expressions.

### Steps to reproduce the issue

```python
from pyomo.environ import *
from pyomo.contrib.appsi.fbbt import IntervalTightener

m = ConcreteModel()
m.x = Var()
m.e = Expression(expr=m.x+1)
m.f = Expression(expr=m.e)
m.c = Constraint(expr=(0, m.f, None))

it = IntervalTightener()
it.set_instance(m) 
```

### Error Message

```console
Traceback (most recent call last):
  File "/Users/bknueven/Software/pyomo_test.py", line 11, in <module>
    it.set_instance(m)
  File "/Users/bknueven/Software/pyomo/pyomo/contrib/appsi/fbbt.py", line 120, in set_instance
    self.add_block(model)
  File "/Users/bknueven/Software/pyomo/pyomo/contrib/appsi/base.py", line 1114, in add_block
    self.add_constraints(
  File "/Users/bknueven/Software/pyomo/pyomo/contrib/appsi/base.py", line 1032, in add_constraints
    self._add_constraints(cons)
  File "/Users/bknueven/Software/pyomo/pyomo/contrib/appsi/fbbt.py", line 158, in _add_constraints
    cmodel.process_fbbt_constraints(
AttributeError: 'ScalarExpression' object has no attribute 'constant'. Did you mean: 'construct'?
```

### Information on your system

Pyomo version: 6.7.2.dev0 (56a8380b891617907f4d06f717b57c4f22f9a691)
Python version: 3.10.13
Operating system: macOS
How Pyomo was installed (PyPI, conda, source): source
Solver (if applicable): N/A

### Additional information

The recursion here seems to be the root cause of the issue:
https://github.com/Pyomo/pyomo/blob/56a8380b891617907f4d06f717b57c4f22f9a691/pyomo/contrib/appsi/cmodel/src/expression.cpp#L1614
which for `m.f` above happy marches up `m.f.expr.expr` until it finds the `LinearExpression` `m.x + 1`. The ultimately returned `cmodel` object is a `LinearOperator`, but the associated pyomo expression is still `m.f`.

**Comment by bknueven** [comment]
A potential resolution would be to mirror the recursion in `build_expression_tree`:
```diff
diff --git a/pyomo/contrib/appsi/cmodel/src/expression.cpp b/pyomo/contrib/appsi/cmodel/src/expression.cpp
index 234ef47e8..f1446c6a2 100644
--- a/pyomo/contrib/appsi/cmodel/src/expression.cpp
+++ b/pyomo/contrib/appsi/cmodel/src/expression.cpp
@@ -1789,7 +1789,8 @@ int build_expression_tree(py::handle pyomo_expr,
 
   if (expr_types.expr_type_map[py::type::of(pyomo_expr)].cast<ExprType>() ==
       named_expr)
-    pyomo_expr = pyomo_expr.attr("expr");
+    return build_expression_tree(pyomo_expr.attr("expr"), appsi_expr, var_map,
+                                 param_map, expr_types);
 
   if (appsi_expr->is_leaf()) {
     ;
```
