### ISSUE TITLE
SolverFactory failing with 'highs'

### ISSUE THREAD

**Issue by kutlay** [Pyomo/pyomo#3286]
## Summary

When I try to use 'highs' using the SolverFactory, "asl" exits unexpectedly. Everything works fine when I use the Highs class from `pyomo.contrib.appsi.solvers.highs`

I have highs 1.7.0 installed on my system:
```
akutlay@Atalays-MacBook-Pro pyomo-new-issue % highs --version
HiGHS version 1.7.0 Githash n/a. Copyright (c) 2024 HiGHS under MIT licence terms
```

### Steps to reproduce the issue

Run the following code:
```
import pyomo.environ as pe
from pyomo.environ import value
from pyomo.opt.results import SolverResults
from pyomo.contrib.appsi.solvers.highs import Highs

m = pe.ConcreteModel()
m.x = pe.Var(domain = pe.Binary)
m.y = pe.Var(domain = pe.Binary)
m.fx = pe.Var(domain = pe.NonNegativeReals)
m.fy = pe.Var(domain = pe.NonNegativeReals)
m.c1 = pe.Constraint(expr = m.fx <= m.x)
m.c2 = pe.Constraint(expr = m.fy <= m.y)
m.c3 = pe.Constraint(expr = m.x + m.y <= 1)

m.obj = pe.Objective(
    expr = m.fx * 0.5 + m.fy * 0.4, 
    sense = pe.maximize,
)

# No issues
opt = Highs()
res = opt.solve(m)

assert value(m.obj) == 0.5

# I get the "asl" did not exit normally error
opt = pe.SolverFactory('highs')
res = opt.solve(m)

assert value(m.obj) == 0.5
```

### Error Message

```
ERROR: Solver (asl) returned non-zero return code (255)
ERROR: Solver log: ERROR:   Error parsing options: Option ‘A’ does not exist
Traceback (most recent call last):
  File "/Users/akutlay/git/pyomo-new-issue/test.py", line 28, in <module>
    test_to_fail()
  File "/Users/akutlay/git/pyomo-new-issue/test.py", line 22, in test_to_fail
    res = opt.solve(m)
          ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pyomo/opt/base/solvers.py", line 628, in solve
    raise ApplicationError("Solver (%s) did not exit normally" % self.name)
pyomo.common.errors.ApplicationError: Solver (asl) did not exit normally
```

### Information on your system

Pyomo version: Pyomo 6.7.3 (CPython 3.12.2 on Darwin 23.3.0)
Python version: 3.12.2
Operating system: MacOS
How Pyomo was installed (PyPI, conda, source): pypi
Solver (if applicable): HiGHS 1.7.0

**Comment by kutlay** [comment]
To add:

Here is the mps file generated by pyomo:
```
* Source:     Pyomo MPS Writer
* Format:     Free MPS
*
NAME unknown
OBJSENSE
 MAX
ROWS
 N  x5
 L  c_u_x6_
 L  c_u_x7_
 L  c_u_x8_
COLUMNS
     x1 c_u_x6_ -1
     x1 c_u_x8_ 1
     x2 c_u_x7_ -1
     x2 c_u_x8_ 1
     x3 x5 0.5
     x3 c_u_x6_ 1
     x4 x5 0.40000000000000002
     x4 c_u_x7_ 1
RHS
     RHS c_u_x6_ 0
     RHS c_u_x7_ 0
     RHS c_u_x8_ 1
BOUNDS
 BV BOUND x1
 BV BOUND x2
 LO BOUND x3 0
 LO BOUND x4 0
ENDATA

```

When I pass this to highs myself, I get the correct results:

```
Running HiGHS 1.7.0 (git hash: n/a): Copyright (c) 2024 HiGHS under MIT licence terms
Number of BV entries in BOUNDS section is 2
MIP  test has 3 rows; 4 cols; 6 nonzeros; 2 integer variables
Coefficient ranges:
  Matrix [1e+00, 1e+00]
  Cost   [4e-01, 5e-01]
  Bound  [1e+00, 1e+00]
  RHS    [1e+00, 1e+00]
Presolving model
3 rows, 4 cols, 6 nonzeros  0s
0 rows, 1 cols, 0 nonzeros  0s
0 rows, 0 cols, 0 nonzeros  0s
Presolve: Optimal

Solving report
  Status            Optimal
  Primal bound      0.5
  Dual bound        0.5
  Gap               0% (tolerance: 0.01%)
  Solution status   feasible
                    0.5 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            0.00 (total)
                    0.00 (presolve)
                    0.00 (postsolve)
  Nodes             0
  LP iterations     0 (total)
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)
Running HiGHS 1.7.0 (git hash: n/a): Copyright (c) 2024 HiGHS under MIT licence terms
Number of BV entries in BOUNDS section is 2
MIP  test has 3 rows; 4 cols; 6 nonzeros; 2 integer variables
Coefficient ranges:
  Matrix [1e+00, 1e+00]
  Cost   [4e-01, 5e-01]
  Bound  [1e+00, 1e+00]
  RHS    [1e+00, 1e+00]
Presolving model
3 rows, 4 cols, 6 nonzeros  0s
0 rows, 1 cols, 0 nonzeros  0s
0 rows, 0 cols, 0 nonzeros  0s
Presolve: Optimal

Solving report
  Status            Optimal
  Primal bound      0.5
  Dual bound        0.5
  Gap               0% (tolerance: 0.01%)
  Solution status   feasible
                    0.5 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            0.00 (total)
                    0.00 (presolve)
                    0.00 (postsolve)
  Nodes             0
  LP iterations     0 (total)
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)
```

**Comment by jsiirola** [comment]
I believe this is expected: the HiGHS interface is currently only available through APPSI. The APPSI solvers are registered with names prepended by `appsi_` in the general (legacy) SolverFactory. So you should create it with

```
solver = SolverFactory(“appsi_highs”)
```

**Comment by liam-veitch** [comment]
The appsi-highs solver with legacy solver does not handle quadratic constraints at least on my windows machine. This error is more likely to do with the version of highs being used. For example, solverfactory("highs") is fine with Highs 1.5 but exhibits similar issues as described above if instead I use the latest 1.7 binary.

> I believe this is expected: the HiGHS interface is currently only available through APPSI. The APPSI solvers are registered with names prepended by `appsi_` in the general (legacy) SolverFactory. So you should create it with
> 
> ```
> solver = SolverFactory(“appsi_highs”)
> ```

**Comment by jsiirola** [comment]
`SolverFactory('highs')` is falling back on using a generic ASL (AMPL Solver Library) interface.  If you have a HiGHS binary (called `highs` - or `highs.exe` on Windows) that is compiled against the ASL, then that *should* work.  It sounds like your installation of HiGHS 1.5 had such a binary, and the 1.7 distribution does not.
