### ISSUE TITLE
`solver_io="python"` fails with the newest gurobi version

### ISSUE THREAD

**Issue by irm-codebase** [Pyomo/pyomo#3414]
## Summary

Using `pyomo`  and `gurobi` will fail when `solver_io="python"` is specified.
This seems to only occur in gurobi 12.0 and pyomo 6.8

### Steps to reproduce the issue

Run the following code with the newest (to date) versions of gurobi and pyomo.

```python
# test.py
import pyomo.environ as pyo

# Create a simple model
model = pyo.ConcreteModel()

# Define decision variables (non-negative integer quantities of products A and B)
model.xA = pyo.Var(within=pyo.NonNegativeReals)  # Product A quantity
model.xB = pyo.Var(within=pyo.NonNegativeReals)  # Product B quantity

# Define the objective function (maximize profit)
model.profit = pyo.Objective(expr=40 * model.xA + 30 * model.xB, sense=pyo.maximize)

# Define the constraints
model.resource1 = pyo.Constraint(expr=2 * model.xA + 4 * model.xB <= 10)  # Resource 1 constraint
model.resource2 = pyo.Constraint(expr=3 * model.xA + 2 * model.xB <= 12)  # Resource 2 constraint

# Create a solver (using GLPK solver for example)
solver = pyo.SolverFactory('gurobi', solver_io='python')

# Solve the model
solver.solve(model)

# Output results
print("Optimal production of Product A:", model.xA())
print("Optimal production of Product B:", model.xB())
print("Maximum profit:", model.profit())

```

### Error Message

```console
Traceback (most recent call last):
  File "/home/ivanruizmanuel/Documents/git/calliope/outputs/test.py", line 21, in <module>
    solver.solve(model)
  File "/home/ivanruizmanuel/miniforge3/envs/calliope/lib/python3.12/site-packages/pyomo/solvers/plugins/solvers/direct_solver.py", line 130, in solve
    self._presolve(*args, **kwds)
  File "/home/ivanruizmanuel/miniforge3/envs/calliope/lib/python3.12/site-packages/pyomo/solvers/plugins/solvers/direct_solver.py", line 68, in _presolve
    self._set_instance(model, kwds)
  File "/home/ivanruizmanuel/miniforge3/envs/calliope/lib/python3.12/site-packages/pyomo/solvers/plugins/solvers/gurobi_direct.py", line 472, in _set_instance
    self._add_block(model)
  File "/home/ivanruizmanuel/miniforge3/envs/calliope/lib/python3.12/site-packages/pyomo/solvers/plugins/solvers/gurobi_direct.py", line 490, in _add_block
    DirectOrPersistentSolver._add_block(self, block)
  File "/home/ivanruizmanuel/miniforge3/envs/calliope/lib/python3.12/site-packages/pyomo/solvers/plugins/solvers/direct_or_persistent_solver.py", line 229, in _add_block
    self._add_constraint(con)
  File "/home/ivanruizmanuel/miniforge3/envs/calliope/lib/python3.12/site-packages/pyomo/solvers/plugins/solvers/gurobi_direct.py", line 545, in _add_constraint
    gurobipy_con = self._solver_model.addConstr(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/gurobipy/_model.pyx", line 3894, in gurobipy._model.Model.addConstr
TypeError: addConstr() got an unexpected keyword argument 'sense'
```

### Information on your system

Pyomo version: 6.8.0
Python version: 3.12.7
Operating system: Linux Fedora 41
How Pyomo was installed (PyPI, conda, source): mamba / conda
Solver (if applicable): gurobi 12.0.0

### Additional information

As an additional test, just change solver to `solver = pyo.SolverFactory('gurobi')` (without `solver_io`). The test will run.

**Comment by blnicho** [comment]
@irm-codebase could you try running against the Pyomo main branch and see if this is resolved? We are planning to cut a release this week (likely today) that should fix this.

**Comment by irm-codebase** [comment]
@blnicho just ran a test using my example. Passed without a hitch.

**Comment by blnicho** [comment]
@irm-codebase Pyomo 6.8.1 is up on PyPI and will be up on conda-forge momentarily so I'm going to close this.

**Comment by irm-codebase** [comment]
Many thanks for the help!
