### ISSUE TITLE
Possible bug in the nl writter

### ISSUE THREAD

**Issue by andrewlee94** [Pyomo/pyomo#350]
I am getting an error from what appears to be the nl writer when trying to solve a Block in my model. This is an IDAES related model, and the code can be found on a branch of the IDAES repo for those with access:

https://github.com/IDAES/idaes/tree/bug_demos/examples/core/Framework_Examples

The main model file is framework_example.py

The error occurs when I try to solve a sub-Block in the model (`C01.holdup_mixer`) in order to initialize it, however the solver runs correctly for the full model. I have narrowed the offending section down to the following Constraint:

`C01.holdup_mixer.energy_mixing` (which is created in idaes.core.ports.InletMixer)

This Constraint does reference an Expression in another part of the model, and this is my only idea of what might be the problem. The traceback is below:

Traceback (most recent call last):
  File "framework_example.py", line 199, in <module>
    main()
  File "framework_example.py", line 177, in main
    outlvl=1)
  File "/home/alee/IDAES Repository/idaes/idaes/models/pressure_changer.py", line 337, in initialize
    optarg=optarg)
  File "/home/alee/IDAES Repository/idaes/idaes/models/pressure_changer.py", line 432, in init_isentropic
    state_args=state_args)
  File "/home/alee/IDAES Repository/idaes/idaes/core/holdup.py", line 820, in initialize
    state_args=state_args)
  File "/home/alee/IDAES Repository/idaes/idaes/core/ports.py", line 218, in initialize
    results = opt.solve(blk, tee=stee)
  File "/home/alee/anaconda2/lib/python2.7/site-packages/pyomo/opt/base/solvers.py", line 599, in solve
    self._presolve(*args, **kwds)
  File "/home/alee/anaconda2/lib/python2.7/site-packages/pyomo/opt/solver/shellcmd.py", line 196, in _presolve
    OptSolver._presolve(self, *args, **kwds)
  File "/home/alee/anaconda2/lib/python2.7/site-packages/pyomo/opt/base/solvers.py", line 696, in _presolve
    **kwds)
  File "/home/alee/anaconda2/lib/python2.7/site-packages/pyomo/opt/base/solvers.py", line 767, in _convert_problem
    **kwds)
  File "/home/alee/anaconda2/lib/python2.7/site-packages/pyomo/opt/base/convert.py", line 110, in convert_problem
    problem_files, symbol_map = converter.apply(*tmp, **tmpkw)
  File "/home/alee/anaconda2/lib/python2.7/site-packages/pyomo/solvers/plugins/converter/model.py", line 192, in apply
    io_options=io_options)
  File "/home/alee/anaconda2/lib/python2.7/site-packages/pyomo/core/base/block.py", line 1668, in write
    io_options)
  File "/home/alee/anaconda2/lib/python2.7/site-packages/pyomo/repn/plugins/ampl/ampl_.py", line 392, in __call__
    include_all_variable_bounds=include_all_variable_bounds)
  File "/home/alee/anaconda2/lib/python2.7/site-packages/pyomo/repn/plugins/ampl/ampl_.py", line 960, in _print_model_NL
    list(self_varID_map[id(var)] for var in ampl_repn._linear_vars),
  File "/home/alee/anaconda2/lib/python2.7/site-packages/pyomo/repn/plugins/ampl/ampl_.py", line 960, in <genexpr>
    list(self_varID_map[id(var)] for var in ampl_repn._linear_vars),
KeyError: 140056467532832

**Comment by qtothec** [comment]
This is a known issue, and is related to a few ongoing discussions. Let me track down the issue numbers.

**Comment by jsiirola** [comment]
Thanks @qtothec.  @andrewlee94: the problem is that there is an "optimization" in some of our older writers (LP, NL) that pregenerates the list of variables by walking over the active blocks of the model.  This causes problems in several situations:
- Solving models with active constraints that refer to Vars on deactivated blocks
- Solving models that have Constraints that reference Vars technically stored on other models (or disconnected blocks)
- Attempting to solve a sub-block in a model where constraints within the sub-block tree reference Vars stored elsewhere on the model.

We are working on fixes...

**Comment by NexusMaxus** [comment]
so what is the fix?

**Comment by blnicho** [comment]
@bernalde just opened an issue that appears to have the same error message. In his small example I think the issue is related to #17 where a Param is used as an index. @andrewlee94 do you remember if this IDAES example had the same characteristic?

**Comment by andrewlee94** [comment]
@blnicho I believe the problem I saw here was trying to solve a `Block` which uses a `Var` on another `Block` which was not part of the solve. This will always produce the above error if the external `Var` is unfixed (if it is fixed, the solver writer treats it as a constant and processes it out correctly).

This bug in #1003 seems to be something different, as it seems to revolve around how the writer is handling the index. Given the `Param` is immutable I would guess this has to be some bug giving a similar erro, as in any other situation the `Param` would be processed out as a constant.

**Comment by mrmundt** [comment]
The NL writer was re-written. We believe this issue has been resolved.
