### ISSUE TITLE
import fails on v 5.4.1 on mac 10.12.6 with python 2.7.10

### ISSUE THREAD

**Issue by josiahjohnston** [Pyomo/pyomo#377]
Pyomo version 5.4.1 fails when installed in a clean environment because the file `pyomo/version/info.py` references `releaselevel` before defining it. Lines 19-20 are the likely culprits with:

```
#releaselevel='invalid'
_releaselevel='final'
```

Full commands for replicating this bug:

```
siah-laptop:~ josiah$ virtualenv --no-site-packages venv
New python executable in /Users/josiah/venv/bin/python
Installing setuptools, pip, wheel...done.
siah-laptop:~ josiah$ source venv/bin/activate
(venv) siah-laptop:~ josiah$ pip install pyomo --no-cache-dir
Collecting pyomo
  Downloading Pyomo-5.4.1-py2.py3-none-any.whl (1.9MB)
    100% |████████████████████████████████| 1.9MB 7.0MB/s 
Collecting ply (from pyomo)
  Downloading ply-3.11-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 18.7MB/s 
Collecting appdirs (from pyomo)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Collecting PyUtilib>=5.6 (from pyomo)
  Downloading PyUtilib-5.6.2-py2.py3-none-any.whl (245kB)
    100% |████████████████████████████████| 256kB 6.7MB/s 
Collecting six>=1.4 (from pyomo)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting nose (from PyUtilib>=5.6->pyomo)
  Downloading nose-1.3.7-py2-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 10.6MB/s 
Installing collected packages: ply, appdirs, six, nose, PyUtilib, pyomo
Successfully installed PyUtilib-5.6.2 appdirs-1.4.3 nose-1.3.7 ply-3.11 pyomo-5.4.1 six-1.11.0
(venv) siah-laptop:~ josiah$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyomo.environ
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/josiah/venv/lib/python2.7/site-packages/pyomo/environ/__init__.py", line 87, in <module>
    _import_packages()
  File "/Users/josiah/venv/lib/python2.7/site-packages/pyomo/environ/__init__.py", line 72, in _import_packages
    pkg.load()
  File "/Users/josiah/venv/lib/python2.7/site-packages/pyomo/opt/plugins/__init__.py", line 12, in load
    import pyomo.opt.plugins.driver
  File "/Users/josiah/venv/lib/python2.7/site-packages/pyomo/opt/plugins/driver.py", line 14, in <module>
    import pyomo.scripting.pyomo_parser
  File "/Users/josiah/venv/lib/python2.7/site-packages/pyomo/scripting/pyomo_parser.py", line 98, in <module>
    _pyomo_parser.add_argument("--version", action="version", version=get_version())
  File "/Users/josiah/venv/lib/python2.7/site-packages/pyomo/scripting/pyomo_parser.py", line 58, in get_version
    from pyomo.version import version
  File "/Users/josiah/venv/lib/python2.7/site-packages/pyomo/version/__init__.py", line 21, in <module>
    from pyomo.version.info import version, version_info, __version__
  File "/Users/josiah/venv/lib/python2.7/site-packages/pyomo/version/info.py", line 23, in <module>
    if releaselevel == 'final':
NameError: name 'releaselevel' is not defined
>>> exit()
(venv) siah-laptop:~ josiah$ head -23 /Users/josiah/venv/lib/python2.7/site-packages/pyomo/version/info.py
#  ___________________________________________________________________________
#
#  Pyomo: Python Optimization Modeling Objects
#  Copyright 2017 National Technology and Engineering Solutions of Sandia, LLC
#  Under the terms of Contract DE-NA0003525 with National Technology and 
#  Engineering Solutions of Sandia, LLC, the U.S. Government retains certain 
#  rights in this software.
#  This software is distributed under the 3-clause BSD License.
#  ___________________________________________________________________________

_init_url="$URL$"

# The micro number should be set when tagging a release or generating a
# VOTD build. releaselever should be left at 'invalid' for trunk
# development and set to 'final' for releases.
major=5
minor=4
micro=1
#releaselevel='invalid'
_releaselevel='final'
serial=0

if releaselevel == 'final':
```

**Comment by qtothec** [comment]
This is a known issue. https://github.com/Pyomo/pyomo/commit/eee63cddcb7072197213bd46ef72450410de9156 on master addresses it. Hopefully 5.4.2 will be released soon.

**Comment by ghackebeil** [comment]
The latest version, now Pyomo 5.4.3, is up on PyPI and seems to be working.
