### ISSUE TITLE
Error raised when solving with 'xpress' solver. Has anyone encountered similar issues?

### ISSUE THREAD

**Issue by KwamiS** [Pyomo/pyomo#409]
Here is the error log:

runfile('C:/Users/kseo/Documents/Python Scripts/BendersPy/runbenders.py', wdir='C:/Users/kseo/Documents/Python Scripts/BendersPy')
Reloaded modules: master, subproblem

Iteration= 1
Traceback (most recent call last):

  File "<ipython-input-9-cdb542efcb6e>", line 1, in <module>
    runfile('C:/Users/kseo/Documents/Python Scripts/BendersPy/runbenders.py', wdir='C:/Users/kseo/Documents/Python Scripts/BendersPy')

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/kseo/Documents/Python Scripts/BendersPy/runbenders.py", line 56, in <module>
    solve_all_instances(solver_manager, 'xpress', sub_insts)

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\opt\parallel\manager.py", line 24, in solve_all_instances
    solver_manager.solve_all(solver, instances, **kwds)

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\opt\parallel\async_solver.py", line 51, in solve_all
    action_handle = self.queue(instance, **kwds)

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\opt\parallel\manager.py", line 122, in queue
    return self._perform_queue(ah, *args, **kwds)

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\opt\parallel\local.py", line 57, in _perform_queue
    results = _opt.solve(*args, **kwds)

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\opt\base\solvers.py", line 631, in solve
    result = self._postsolve()

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\opt\solver\shellcmd.py", line 268, in _postsolve
    results = self.process_output(self._rc)

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\opt\solver\shellcmd.py", line 329, in process_output
    self.process_soln_file(results)

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\solvers\plugins\solvers\XPRESS.py", line 361, in process_soln_file
    if (extract_reduced_costs is True) and (field_name == "reducedCost"):

NameError: name 'field_name' is not defined

**Comment by kdheepak** [comment]
@KwamiS Can you open `C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\solvers\plugins\solvers\XPRESS.py` and change line 361 to the following?

```python
                if (extract_reduced_costs is True) and (variable_name == "reducedCost"):
```

And try running your code again? I'm guessing this will stop the error from being thrown.

`variable_reduced_cost` is not being used anywhere else though. I'm guessing the XPRESS plugin does not support the more advanced features of pyomo.

**Comment by KwamiS** [comment]
@kdheepak  I did implement the proposed change. It passed the 1st iteration but raised the error below:

runfile('C:/Users/kseo/Documents/Python Scripts/BendersPy/runbenders.py', wdir='C:/Users/kseo/Documents/Python Scripts/BendersPy')

Iteration= 1
Profit for scenario=Base Sub-Problem is 179523.0

Profit for scenario=Low Sub-Problem is 125839.0

Profit for scenario=High Sub-Problem is 93830.0

Traceback (most recent call last):

  File "<ipython-input-1-cdb542efcb6e>", line 1, in <module>
    runfile('C:/Users/kseo/Documents/Python Scripts/BendersPy/runbenders.py', wdir='C:/Users/kseo/Documents/Python Scripts/BendersPy')

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/kseo/Documents/Python Scripts/BendersPy/runbenders.py", line 74, in <module>
    inst.urc[inst.Sell[p,t]]

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\core\kernel\component_map.py", line 100, in __getitem__
    % (id(obj), str(obj)))

KeyError: "Component with id '2149761530272': Sell[coils,2]"

**Comment by kdheepak** [comment]
Is that the full traceback? Just looking at that I can't say if that's an issue with the XPRESS plugin, since the traceback does not have any calls from the XPRESS.py file. Did you say this worked with the CPLEX solver interface? Can you confirm by changing **just** the solver name so see if this error occurs only with XPRESS. 

( P.S. :

You can use a backtick block to make your code / traceback blocks formatted on GitHub.

````
```python
print("hello world")
```
````

The above block would show up as the following.

```python
print("hello world")
```

It can make it easier to read.

)

**Comment by KwamiS** [comment]
@kdheepak Yes it did work with CPLEX.

Here is the formatted output with Xpress

``` python
runfile('C:/Users/kseo/Documents/Python Scripts/BendersPy/runbenders.py', wdir='C:/Users/kseo/Documents/Python Scripts/BendersPy')

Iteration= 1
 Profit for scenario=Base Sub-Problem is 179523.0

Profit for scenario=Low Sub-Problem is 125839.0

Profit for scenario=High Sub-Problem is 93830.0

Traceback (most recent call last):

File "", line 1, in 
 runfile('C:/Users/kseo/Documents/Python Scripts/BendersPy/runbenders.py', wdir='C:/Users/kseo/Documents/Python Scripts/BendersPy')

File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
 execfile(filename, namespace)

File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
 exec(compile(f.read(), filename, 'exec'), namespace)

File "C:/Users/kseo/Documents/Python Scripts/BendersPy/runbenders.py", line 74, in 
 inst.urc[inst.Sell[p,t]]

File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\core\kernel\component_map.py", line 100, in getitem
 % (id(obj), str(obj)))

KeyError: "Component with id '2149761530272': Sell[coils,2]"
```

**Comment by KwamiS** [comment]
@kdheepak  Here is the output with GLPK

```python
runfile('C:/Users/kseo/Documents/Python Scripts/BendersPy/runbenders.py', wdir='C:/Users/kseo/Documents/Python Scripts/BendersPy')
Reloaded modules: master, subproblem

Iteration= 1
Profit for scenario=Base Sub-Problem is 179523.0

Profit for scenario=Low Sub-Problem is 125839.0

Profit for scenario=High Sub-Problem is 93830.0

Traceback (most recent call last):

  File "<ipython-input-2-cdb542efcb6e>", line 1, in <module>
    runfile('C:/Users/kseo/Documents/Python Scripts/BendersPy/runbenders.py', wdir='C:/Users/kseo/Documents/Python Scripts/BendersPy')

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/kseo/Documents/Python Scripts/BendersPy/runbenders.py", line 74, in <module>
    inst.urc[inst.Sell[p,t]]

  File "C:\Users\kseo\AppData\Local\Continuum\anaconda3\lib\site-packages\pyomo\core\kernel\component_map.py", line 100, in __getitem__
    % (id(obj), str(obj)))

KeyError: "Component with id '2149762404840': Sell[coils,2]"

```

**Comment by kdheepak** [comment]
It appears to be a similar error with XPRESS and GLPK. If someone from the Pyomo team can chime in that would be great.

**Comment by blnicho** [comment]
@KwamiS if you're still having trouble with this could you post a minimal example that recreates the error? Is the `runbenders.py` script something that you wrote?

**Comment by blnicho** [comment]
No response on this in the last 5 months so closing it. @KwamiS feel free to open a new issue if you are still having trouble.
