### ISSUE TITLE
identify_variables giving AttributeError

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#482]
Working off of master: https://github.com/Pyomo/pyomo/commit/c6edd105cba9745d4227e468155cadef54f48988

# Input
```
from pyomo.environ import *
from pyomo.core.base.expr import identify_variables
m = ConcreteModel()
m.x = Var()
m.c = Constraint(expr=m.x >= 2)
vars = list(identify_variables(m.c.body))
print(vars)
```

# Output
```
[qchen@britnyfox pyomo]$ python test.py
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    vars = list(identify_variables(m.c.body))
  File "/home/qchen/git/pyomo/pyomo/core/kernel/expr_coopr3.py", line 83, in identify_variables
AttributeError: 'SimpleVar' object has no attribute 'is_expression'
```

**Comment by qtothec** [comment]
After talking with @blnicho, it looks like this is an artefact of the function path change together with the presence of old lingering *.pyc files.
