### ISSUE TITLE
Error in installation of pyomo extras package in windows 10

### ISSUE THREAD

**Issue by anishibu** [Pyomo/pyomo#601]
I am trying to install pyomo "extras" package using command prompt in windows with the following command : pyomo install-extras
But I am getting the following error:
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pyomo.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\pyomo\scripting\pyomo_main.py", line 82, in main
    retval = _options.func(_options)
  File "c:\python27\lib\site-packages\pyomo\scripting\driver_help.py", line 46, in install_extras_exec
    pyutilib.subprocess.run(command, tee=True)
  File "c:\python27\lib\site-packages\pyutilib\subprocess\processmngr.py", line 659, in run_command
    (' '.join(_cmd), err))
pyutilib.common._exceptions.ApplicationError: Could not execute the command: 'c:\python27\get_pyomo_extras'
        Error message: [Error 2] The system cannot find the file specified

Can anybody kindly help me out?

**Comment by qtothec** [comment]
I think the developers were all waiting on each other to answer. Most of us here don't develop on Windows that often. From the stack trace, it looks like python was unable to find a particular file. How did you go about installing Pyomo in the first place? Was it through Anaconda? If so, you should try running the command from the Anaconda Prompt.

**Comment by whart222** [comment]
The problem is that Pyomo installs the get_pyomo_extras script.  If you could help confirm where that script is installed, and give us details on how you installed Pyomo, that would help us diagnose this issue.

**Comment by whart222** [comment]
But ... once you find that script, you should be able to launch it directly.

**Comment by blnicho** [comment]
Closing this due to inactivity.
