### ISSUE TITLE
Failed to run model inside Flask server

### ISSUE THREAD

**Issue by bbrunaud** [Pyomo/pyomo#609]
Hello

I wrote a small package to solve a model. It works perfectly. But, when I tried embedding it into a webapp using Flask I got the following error:

```python
RuntimeError: Attempting to use an unavailable solver.

The SolverFactory was unable to create the solver "cbc"
and returned an UnknownSolver object.  This error is raised at the point
where the UnknownSolver object was used as if it were valid (by calling
method "solve").

The original solver was created with the following parameters:
        type: cbc
        _args: ()
        options: {}
```

I know this might be Flask related issue, but I was wondering If anyone had run into the same issue before.

thanks

**Comment by jwatsonnm** [comment]
This usually means that the “cbc” executable is not in your PATH environment variable.

jpw

**Comment by bbrunaud** [comment]
Hi JP

Yes, the solvers are in the PATH. The package works when it's not embedded in the web app, but it fails inside. I tried creating the solvers in the main scope of the package and now the error changed. Here is the traceback

```python
Optimizing Line Assignment...
[2018-07-16 09:26:06,968] ERROR in app: Exception on /uploader [POST]
Traceback (most recent call last):
  File "C:\Users\bbrunaud\AppData\Roaming\Python\Python36\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\bbrunaud\AppData\Roaming\Python\Python36\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\bbrunaud\AppData\Roaming\Python\Python36\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\bbrunaud\AppData\Roaming\Python\Python36\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\bbrunaud\AppData\Roaming\Python\Python36\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\bbrunaud\AppData\Roaming\Python\Python36\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:\Python\Flask_app\flaskapp.py", line 44, in uploader
    optimize_line_assignment(m)
  File "H:\Python\optim\optim\line_assignment.py", line 90, in optimize_line_assignment
    mip.solve(m)
  File "C:\Users\bbrunaud\AppData\Roaming\Python\Python36\site-packages\pyomo\opt\base\solvers.py", line 608, in solve
    _status = self._apply_solver()
  File "C:\Users\bbrunaud\AppData\Roaming\Python\Python36\site-packages\pyomo\opt\solver\shellcmd.py", line 242, in _apply_solver
    self._rc, self._log = self._execute_command(self._command)
  File "C:\Users\bbrunaud\AppData\Roaming\Python\Python36\site-packages\pyomo\opt\solver\shellcmd.py", line 305, in _execute_command
    tee   = self._tee
  File "C:\Users\bbrunaud\AppData\Roaming\Python\Python36\site-packages\pyutilib\subprocess\processmngr.py", line 544, in run_command
    = signal.signal(signal.SIGINT, handler)
  File "c:\program files\python36\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

**Comment by jsiirola** [comment]
This is related to how `pyutilib.subprocess` handles signals.  See https://github.com/PyUtilib/pyutilib/issues/31#issuecomment-382479024 for the discussion & fix.

(The short answer is you have to tell pyutilib to *not* handle signals when you are running within a webapp that does not support signals.)

**Comment by blnicho** [comment]
@bbrunaud did John's comment resolve this?

**Comment by bbrunaud** [comment]
It did. Thanks!.

As an alternative, I also changed the web server in Flask from werkzeug (defaulft) to tornado, which does support multi threading.

**Comment by SebastianJHM** [comment]
Thank you @jsiirola. This solve perfectly the problem.
