### ISSUE TITLE
Bug in expression substitution using clone_expression

### ISSUE THREAD

**Issue by blnicho** [Pyomo/pyomo#640]
Expression substitution does not work for the case where you want to replace a mutable parameter with a variable. Here is a small illustrative example:

```
from pyomo.environ import *
from pyomo.core.expr.current import clone_expression
 
m = ConcreteModel()

m.p = Param(initialize=3, mutable=True)
m.v = Var(bounds=(0,2))
m.v2 = Var(bounds=(0,2))

m.con = Constraint(expr=m.p*m.v <=10)

submap = {id(m.p):m.v2}

m.con2 = Constraint(expr=clone_expression(m.con.expr, substitute=submap))

SolverFactory('ipopt').solve(m)
```

If you `pprint` the model before calling the solver it will appear as if everything worked correctly but the following error is thrown when calling the writer:

```
ERROR: evaluating object as numeric value: v2
        (object: <class 'pyomo.core.base.var.SimpleVar'>)
    No value for uninitialized NumericValue object v2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/blnicho/Research/pyomo/pyomo/opt/base/solvers.py", line 599, in solve
    self._presolve(*args, **kwds)
  File "/home/blnicho/Research/pyomo/pyomo/opt/solver/shellcmd.py", line 196, in _presolve
    OptSolver._presolve(self, *args, **kwds)
  File "/home/blnicho/Research/pyomo/pyomo/opt/base/solvers.py", line 699, in _presolve
    **kwds)
  File "/home/blnicho/Research/pyomo/pyomo/opt/base/solvers.py", line 770, in _convert_problem
    **kwds)
  File "/home/blnicho/Research/pyomo/pyomo/opt/base/convert.py", line 110, in convert_problem
    problem_files, symbol_map = converter.apply(*tmp, **tmpkw)
  File "/home/blnicho/Research/pyomo/pyomo/solvers/plugins/converter/model.py", line 199, in apply
    io_options=io_options)
  File "/home/blnicho/Research/pyomo/pyomo/core/base/block.py", line 1679, in write
    io_options)
  File "/home/blnicho/Research/pyomo/pyomo/repn/plugins/ampl/ampl_.py", line 379, in __call__
    include_all_variable_bounds=include_all_variable_bounds)
  File "/home/blnicho/Research/pyomo/pyomo/repn/plugins/ampl/ampl_.py", line 958, in _print_model_NL
    quadratic=False)
  File "/home/blnicho/Research/pyomo/pyomo/repn/standard_repn.py", line 387, in generate_standard_repn
    repn=repn)
  File "/home/blnicho/Research/pyomo/pyomo/repn/standard_repn.py", line 950, in _generate_standard_repn
    ans = _collect_standard_repn(expr, 1, idMap, compute_values, verbose, quadratic)
  File "/home/blnicho/Research/pyomo/pyomo/repn/standard_repn.py", line 923, in _collect_standard_repn
    return fn(exp, multiplier, idMap, compute_values, verbose, quadratic)
  File "/home/blnicho/Research/pyomo/pyomo/repn/standard_repn.py", line 523, in _collect_term
    val = value(exp._args_[0])
  File "/home/blnicho/Research/pyomo/pyomo/core/expr/numvalue.py", line 225, in value
    % (obj.name,))
ValueError: No value for uninitialized NumericValue object v2
```

Looks like there are some implicit assumptions about which leaf nodes are/aren't variables that are not being updated in the substituter.

**Comment by qtothec** [comment]
Does it work if you use the expression replacement visitor pattern? https://github.com/Pyomo/pyomo/blob/master/pyomo/contrib/preprocessing/plugins/var_aggregator.py#L265

**Comment by blnicho** [comment]
@qtothec yes, it looks like that works for the mutable param --> var case. But digging into this a bit deeper, it doesn't look like either method works for the var --> mutable param case.

**Comment by blnicho** [comment]
This might be related to the design discussion @whart222 wanted to have in #439 about `clone_expression`. Perhaps this function should be deprecated for expression substitution in favor of the expression replacement visitor.

**Comment by gseastream** [comment]
Yes as far as I can tell (by searching) `clone_expression` is only used in the old connector expander.

**Comment by jsiirola** [comment]
I think leaving the function is fine, but we need to reimplement it to call a version of the expression replacement visitor. It won’t be as efficient as it used to be, but because pyomo5 expressions store state in the tree, we can no longer rely on deepcopy when performing substitutions.
