### ISSUE TITLE
'ConcreteModel' object has no attribute 'as_concrete_model'

### ISSUE THREAD

**Issue by wanqiuchansheng** [Pyomo/pyomo#713]
rapper throw the following exception!
Traceback (most recent call last):
  File "/home/administrator/project/python/gym-rl/pyomotools/test/pysp/simple_quadratic/run.py", line 10, in <module>
    stsolver = rapper.StochSolver("ReferenceModel.py")
  File "/home/administrator/.conda/envs/python36/lib/python3.6/site-packages/pyomo/pysp/util/rapper.py", line 91, in __init__
    tree_model = tree.as_concrete_model()
  File "/home/administrator/.conda/envs/python36/lib/python3.6/site-packages/pyomo/core/base/block.py", line 519, in __getattr__
    % (self.__class__.__name__, val))
AttributeError: 'ConcreteModel' object has no attribute 'as_concrete_model'

**Comment by bengadi** [comment]
any response to this issue?

**Comment by blnicho** [comment]
@bengadi this is a 4 year old closed issue. Please open a new issue with the information in the issue template if you would like to report a bug.
