### ISSUE TITLE
Substitutions on a ranged inequality with an Expression on the bound is NOT currently supported

### ISSUE THREAD

**Issue by eacquesta** [Pyomo/pyomo#759]
When applying a substitution within a ranged inequality constraint that has an Expression on the bounds results with an AttributeError (see the following Traceback for the given small use case example).

Example:

```
from pyomo.environ import *
from pyomo.core.expr.current import ExpressionReplacementVisitor

m = ConcreteModel()

m.a = Param(initialize=0, mutable=True)
m.b = Param(initialize=1, mutable=True)

m.x = Var(initialize=1.0)        

m.E = Expression(expr=3*m.a-5)
m.C = Constraint(expr=inequality(m.E,m.x,m.b))

subMap = {id(m.a):m.x}

m.add_component('C_sub', Constraint(expr=ExpressionReplacementVisitor(
                           substitute=subMap,
                           remove_named_expressions=True).dfs_postorder_stack(
                           m.C.lower) <= ExpressionReplacementVisitor(
                           substitute=subMap,
                           remove_named_expressions=
                           True).dfs_postorder_stack(m.C.body))
               )    
```        

Traceback Error:

```
ERROR: Constructing component 'C_sub' from data=None failed: AttributeError:
    'tuple' object has no attribute 'append'
Traceback (most recent call last):
  File "rangInqBigE_substitutions.py", line 26, in <module>
    True).dfs_postorder_stack(m.C.body))
  File "/home/eacques/IDAES/pyomo/pyomo/core/base/block.py", line 1007, in add_component
    val.construct(data)
  File "/home/eacques/IDAES/pyomo/pyomo/core/base/constraint.py", line 753, in construct
    self._setitem_when_not_present(None, tmp)
  File "/home/eacques/IDAES/pyomo/pyomo/core/base/constraint.py", line 706, in _setitem_when_not_present
    index=index, value=value)
  File "/home/eacques/IDAES/pyomo/pyomo/core/base/indexed_component.py", line 667, in _setitem_when_not_present
    obj.set_value(value)
  File "/home/eacques/IDAES/pyomo/pyomo/core/base/constraint.py", line 1050, in set_value
    return super(SimpleConstraint, self).set_value(expr)
  File "/home/eacques/IDAES/pyomo/pyomo/core/base/constraint.py", line 539, in set_value
    self._body -= expr.arg(1)
  File "/home/eacques/IDAES/pyomo/pyomo/core/expr/numvalue.py", line 894, in __isub__
    return _generate_sum_expression(_isub,self,other)
  File "/home/eacques/IDAES/pyomo/pyomo/core/expr/expr_pyomo5.py", line 3280, in _generate_sum_expression
    return _self.add(-_other)
  File "/home/eacques/IDAES/pyomo/pyomo/core/expr/expr_pyomo5.py", line 2502, in add
    self._args_.append(new_arg)
AttributeError: 'tuple' object has no attribute 'append'
```

**Comment by mrmundt** [comment]
We cannot reproduce this issue with the newest version of Pyomo.
