### ISSUE TITLE
Pyomo conda  installation problem on Ubuntu 16.04

### ISSUE THREAD

**Issue by andregirard** [Pyomo/pyomo#860]
I am trying to install pyomo on Ubuntu 16.04 with conda. I have done the following:

- conda update -n root conda
- conda update --all
- conda install -c conda-forge pyomo
- conda install -c conda-forge pyomo.extras
- conda install -c conda-forge ipopt coincbc glpk

 I then type pyomo -h and get

`Traceback (most recent call last):
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pyomo/scripting/pyomo_main.py", line 25, in <module>
    plugin_class = entrypoint.load()
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (PyUtilib 5.6.4 (/home/andre/anaconda3/lib/python3.6/site-packages), Requirement.parse('PyUtilib>=5.6.5'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andre/anaconda3/bin/pyomo", line 7, in <module>
    from pyomo.scripting.pyomo_main import main
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pyomo/scripting/pyomo_main.py", line 37, in <module>
    raise ImportError(msg)
ImportError: Error loading pyomo.command entry point pyomo.runbenders = pyomo.pysp.benders:
Original VersionConflict: (PyUtilib 5.6.4 (/home/andre/anaconda3/lib/python3.6/site-packages), Requirement.parse('PyUtilib>=5.6.5'))
Traceback:
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pyomo/scripting/pyomo_main.py", line 25, in <module>
    plugin_class = entrypoint.load()
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
`
Any help for a workaround would be greatly appreciated.

A. Girard

**Comment by blnicho** [comment]
Looks like you have an old version of PyUtilib installed possibly caused by trying to install Pyomo multiple times. Can you update your PyUtilib module?

`conda update pyutilib`

Alternatively, try uninstalling pyomo and pyutilib and trying again in a fresh conda environment.

**Comment by andregirard** [comment]
Unfortunately, neither solution seems to work. Should I scrap my whole anaconda installation and start everything from scratch?

The first solution does not work. 
`conda update pyutilib
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/andre/anaconda3

  added / updated specs:
    - pyutilib


The following packages will be UPDATED:

  ca-certificates    conda-forge::ca-certificates-2018.11.~ --> pkgs/main::ca-certificates-2019.1.23-0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            conda-forge::certifi-2018.11.29-py36_~ --> pkgs/main::certifi-2018.11.29-py36_0
  openssl            conda-forge::openssl-1.1.1a-h14c3975_~ --> pkgs/main::openssl-1.1.1a-h7b6447c_0


Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done


andre@andre-Precision-3520:~$ pyomo -h
Traceback (most recent call last):
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pyomo/scripting/pyomo_main.py", line 25, in <module>
    plugin_class = entrypoint.load()
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (PyUtilib 5.6.4 (/home/andre/anaconda3/lib/python3.6/site-packages), Requirement.parse('PyUtilib>=5.6.5'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andre/anaconda3/bin/pyomo", line 7, in <module>
    from pyomo.scripting.pyomo_main import main
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pyomo/scripting/pyomo_main.py", line 37, in <module>
    raise ImportError(msg)
ImportError: Error loading pyomo.command entry point pyomo.runbenders = pyomo.pysp.benders:
Original VersionConflict: (PyUtilib 5.6.4 (/home/andre/anaconda3/lib/python3.6/site-packages), Requirement.parse('PyUtilib>=5.6.5'))
Traceback:
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pyomo/scripting/pyomo_main.py", line 25, in <module>
    plugin_class = entrypoint.load()
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)`


The second solution 
`conda uninstall pyomo
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/andre/anaconda3

  removed specs:
    - pyomo


The following packages will be REMOVED:

  pyomo-5.6.1-py36_3


Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
`

and then 
`conda uninstall pyutilib
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/andre/anaconda3

  removed specs:
    - pyutilib


The following packages will be REMOVED:

  pyutilib-5.6.4-py36_0


Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
`

Then re-install pyutilib

`conda install pyutilib
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/andre/anaconda3

  added / updated specs:
    - pyutilib


The following NEW packages will be INSTALLED:

  pyutilib           pkgs/main/linux-64::pyutilib-5.6.4-py36_0


Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
`

and then pyomo

`conda install -c conda-forge pyomo
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/andre/anaconda3

  added / updated specs:
    - pyomo


The following NEW packages will be INSTALLED:

  pyomo              conda-forge/linux-64::pyomo-5.6.1-py36_3

The following packages will be UPDATED:

  certifi              pkgs/main::certifi-2018.11.29-py36_0 --> conda-forge::certifi-2018.11.29-py36_1000
  numpy              pkgs/main::numpy-1.15.4-py36h99e49ec_0 --> conda-forge::numpy-1.16.1-py36_blas_openblash1522bff_0
  openssl              pkgs/main::openssl-1.1.1a-h7b6447c_0 --> conda-forge::openssl-1.1.1a-h14c3975_1000
  scikit-learn       pkgs/main::scikit-learn-0.20.2-py36h2~ --> conda-forge::scikit-learn-0.20.2-py36_blas_openblashebff5e3_1400
  scipy               pkgs/main::scipy-1.2.0-py36he2b7bc3_0 --> conda-forge::scipy-1.2.0-py36_blas_openblash1522bff_1201

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2019.1.23-0 --> conda-forge::ca-certificates-2018.11.29-ha4d7672_0


Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
`

Still does not work

`pyomo -h
Traceback (most recent call last):
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pyomo/scripting/pyomo_main.py", line 25, in <module>
    plugin_class = entrypoint.load()
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (PyUtilib 5.6.4 (/home/andre/anaconda3/lib/python3.6/site-packages), Requirement.parse('PyUtilib>=5.6.5'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andre/anaconda3/bin/pyomo", line 7, in <module>
    from pyomo.scripting.pyomo_main import main
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pyomo/scripting/pyomo_main.py", line 37, in <module>
    raise ImportError(msg)
ImportError: Error loading pyomo.command entry point pyomo.runbenders = pyomo.pysp.benders:
Original VersionConflict: (PyUtilib 5.6.4 (/home/andre/anaconda3/lib/python3.6/site-packages), Requirement.parse('PyUtilib>=5.6.5'))
Traceback:
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pyomo/scripting/pyomo_main.py", line 25, in <module>
    plugin_class = entrypoint.load()
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/andre/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
`

**Comment by blnicho** [comment]
Could you post the output of `conda list pyomo` and `conda list pyutilib`? I just tested uninstalling and reinstalling Pyomo and PyUtilib in my own conda environment and I was able to find and install PyUtilib 5.6.5 just fine.

**Comment by andregirard** [comment]
Here it is. 
`conda list pyomo
packages in environment at /home/andre/anaconda3:

Name                    Version                   Build  Channel
pyomo                     5.6.1                    py36_3    conda-forge
pyomo.extras              3.3                 py36_182212    conda-forge

andre@andre-Precision-3520:~$ conda list pyutilib
 packages in environment at /home/andre/anaconda3:

Name                    Version                   Build  Channel
pyutilib                  5.6.4                    py36_0  
`

**Comment by jsiirola** [comment]
Instead of upgrading, try uninstall and reinstall:
```
conda uninstall pyomo pyomo-extras pyutilib 
conda install pyomo
```
Also note: do not bother installing Pyomo-extras.

**Comment by andregirard** [comment]
It works now.

Many thanks for you help.
