### ISSUE TITLE
Avoid failing tests on NEOS timeouts

### ISSUE THREAD

**Issue by qtothec** [Pyomo/pyomo#896]
It would make sense not to fail tests for unrelated issues when the NEOS server times out.

@jsiirola - this is the other timeout-related issue that we ran into.

```
======================================================================
ERROR: test_help_solvers (pyomo.scripting.tests.test_cmds.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\pyomo\pyomo\scripting\tests\test_cmds.py", line 23, in test_help_solvers
    help_solvers()
  File "C:\projects\pyomo\pyomo\scripting\driver_help.py", line 373, in help_solvers
    kestrel = pyomo.neos.kestrel.kestrelAMPL()
  File "C:\projects\pyomo\pyomo\neos\kestrel.py", line 113, in __init__
    self.setup_connection()
  File "C:\projects\pyomo\pyomo\neos\kestrel.py", line 137, in setup_connection
    result = self.neos.ping()
  File "C:\Miniconda36\lib\xmlrpc\client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "C:\Miniconda36\lib\xmlrpc\client.py", line 1452, in __request
    verbose=self.__verbose
  File "C:\Miniconda36\lib\xmlrpc\client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Miniconda36\lib\xmlrpc\client.py", line 1187, in single_request
    dict(resp.getheaders())
xmlrpc.client.ProtocolError: <ProtocolError for neos-server.org:3333/RPC2: 504 Gateway Time-out>
```

**Comment by jsiirola** [comment]
I am torn on how to deal with this.  On the surface, I would agree with wrapping the NEOS tests in a `try...except` and swallow the timeout.  However, I worry about that masking real errors in the interface (like the NEOS server moving to a new port number).  Right now, the NEOS timeouts are relatively infrequent so that re-launching the builds is not terrible, so I would be inclined to close this as a wontfix (until the networking problems become larger problems).

**Comment by qtothec** [comment]
Yeah, they're not frequent enough to really be annoying at this point. We can revisit if that changes.
