### ISSUE TITLE
Cloning models with references does not preserve the references correctly

### ISSUE THREAD

**Issue by michaelbynum** [Pyomo/pyomo#912]
The ```_data``` attribute of a reference is of type ```_ReferenceDict``` which has a ```_slice``` attribute which should be an ```_IndexedComponent_slice``` object. However, when a model gets cloned, this ```_slice``` attribute becomes a list. This causes an error when iterating over components in the model:

```
>>> import pyomo.environ as pe
>>> m = pe.ConcreteModel()
>>> m.x = pe.Var()
>>> m.x_ref = pe.Reference(m.x)
>>> m2 = m.clone()
>>> m.x_ref._data._slice
<pyomo.core.base.indexed_component_slice._IndexedComponent_slice object at 0x151fa63438>
>>> m2.x_ref._data._slice
[<pyomo.core.base.var.SimpleVar object at 0x152002b048>]
>>> for v in m.component_data_objects(pe.Var):
...     print(v)
... 
x
x
>>> for v in m2.component_data_objects(pe.Var):
...     print(v)
... 
x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../pyomo/core/base/block.py", line 1342, in component_data_objects
    sort=sort):
  File "/Users/.../pyomo/core/base/block.py", line 1274, in _component_data_iter
    for idx, compData in _items:
  File "/Users/.../pyomo/core/base/indexed_component.py", line 309, in iteritems
    yield key, self[key]
  File "/Users/.../pyomo/core/base/indexed_component.py", line 319, in __getitem__
    obj = self._data.get(index, _NotFound)
  File "/Users/.../_collections_abc.py", line 660, in get
    return self[key]
  File "/Users/.../pyomo/core/base/reference.py", line 178, in __getitem__
    self._get_iter(self._slice, key, get_if_not_present=True)
  File "/Users/.../pyomo/core/base/reference.py", line 292, in _get_iter
    get_if_not_present=get_if_not_present)
  File "/Users/.../pyomo/core/base/indexed_component_slice.py", line 265, in __init__
    call_stack = self._slice._call_stack
AttributeError: 'list' object has no attribute '_call_stack'

```

**Comment by qtothec** [comment]
Ah, I can see some reasons why this might be problematic.

**Comment by michaelbynum** [comment]
The problem appears to be that ```_IndexedComponent_slice.__getattr__``` returns ```self``` even for attributes such as ```__deepcopy__``` and ```__getstate__```.

**Comment by jsiirola** [comment]
Yeah - this is definitely a bug.  A patch / PR should be easy to put together - I hope it will be up in an hour or two.

**Comment by michaelbynum** [comment]
@jsiirola Thanks. I have been trying to fix it myself, but I have been unsuccessful so far.
