### ISSUE TITLE
ExternalFunction and DAE Transformation

### ISSUE THREAD

**Issue by eslickj** [Pyomo/pyomo#93]
I think there is a problem applying DAE transformations to Pyomo models with ExternalFunction objects.  I can come up with a simpler demonstration, but hopefully the trace below is good enough.

jeslick@pds04:~/git/eslickj/models/idaes_models/process/solvent/MEA_simple> python main.py 
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    flowsheet = init(filename=args.load_json)
  File "main.py", line 34, in init
    flowsheet = MeaSheet(name='MEA_Model', solver=solver)
  File "/imports/users/jeslick/git/eslickj/models/idaes_models/process/solvent/MEA_simple/flowsheet.py", line 51, in __init__
    FlowsheetModel.__init__(self, *args, **kwargs)
  File "/imports/users/jeslick/git/eslickj/models/idaes_models/core/flowsheet_model.py", line 29, in __init__
    self.build()
  File "/imports/users/jeslick/git/eslickj/models/idaes_models/process/solvent/MEA_simple/flowsheet.py", line 341, in build
    doc="CO2 absorber"))
  File "/imports/users/jeslick/git/eslickj/models/idaes_models/unit/solvent/MEA_simple/column.py", line 123, in __init__
    self.build()
  File "/imports/users/jeslick/git/eslickj/models/idaes_models/unit/solvent/MEA_simple/column.py", line 164, in build
    self._fd_transform()
  File "/imports/users/jeslick/git/eslickj/models/idaes_models/unit/solvent/MEA_simple/column.py", line 347, in _fd_transform
    blk, nfe=self.nfe, wrt=blk.z, scheme='BACKWARD')
  File "/imports/users/jeslick/anaconda2/lib/python2.7/site-packages/pyomo/core/base/plugin.py", line 330, in apply_to
    self._apply_to(model, **kwds)
  File "/imports/users/jeslick/anaconda2/lib/python2.7/site-packages/pyomo/dae/plugins/finitedifference.py", line 170, in _apply_to
    self._transformBlock(block,currentds)
  File "/imports/users/jeslick/anaconda2/lib/python2.7/site-packages/pyomo/dae/plugins/finitedifference.py", line 199, in _transformBlock
    update_contset_indexed_component(c)
  File "/imports/users/jeslick/anaconda2/lib/python2.7/site-packages/pyomo/dae/misc.py", line 115, in update_contset_indexed_component
    if comp.dim() == 1:
AttributeError: 'AMPLExternalFunction' object has no attribute 'dim'

**Comment by blnicho** [comment]
@eslickj and @jghouse88 I think I have resolved this in the `dae-external-function-fix` branch of Pyomo. Could you check if this works for you? It is branched off of Pyomo master (not the IDAES branch) but the fix was only a couple lines in `misc.py` which can be manually added to your Pyomo checkout temporarily.

**Comment by jghouse88** [comment]
@blnicho Did a quick check with the problem I was trying to solve. The model seems to get built now but I am getting a "Too Few Degrees of Freedom" error and that has more to do with the model than the DAE bug. I will need to look into this further but for now I think that this fix resolves the DAE bug.

**Comment by blnicho** [comment]
@jghouse88 great, I'll open a PR to get it merged then.
